import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from "react";
import ReactDOM from "react-dom/client";
import { BrowserRouter, Routes, Route } from "react-router-dom";
import App from "./App";
import Dashboard from "./pages/Dashboard";
import Patients from "./pages/Patients";
import Appointments from "./pages/Appointments";
import Payments from "./pages/Payments";
import WaivedConsultations from "./pages/WaivedConsultations";
import Events from "./pages/Events";
import AuditDashboard from "./pages/AuditDashboard";
ReactDOM.createRoot(document.getElementById("root")).render(_jsx(React.StrictMode, { children: _jsx(BrowserRouter, { children: _jsx(Routes, { children: _jsxs(Route, { path: "/", element: _jsx(App, {}), children: [_jsx(Route, { index: true, element: _jsx(Dashboard, {}) }), _jsx(Route, { path: "patients", element: _jsx(Patients, {}) }), _jsx(Route, { path: "appointments/today", element: _jsx(Appointments, {}) }), _jsx(Route, { path: "payments/summary", element: _jsx(Payments, {}) }), _jsx(Route, { path: "payments/waived", element: _jsx(WaivedConsultations, {}) }), _jsx(Route, { path: "events", element: _jsx(Events, {}) }), _jsx(Route, { path: "audit-dashboard", element: _jsx(AuditDashboard, {}) })] }) }) }) }));
