# Generated by Django 5.2.7 on 2026-02-02 00:33

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('view', 'View'), ('edit', 'Edit'), ('generate_pdf', 'Generate PDF'), ('emergency_access', 'Emergency Access'), ('emergency_access_refreshed', 'Emergency Access Refreshed'), ('institution_switch', 'Switch Institution')], help_text='Tipo de acción realizada', max_length=50)),
                ('access_level', models.CharField(choices=[('full_access', 'Full Access'), ('emergency_access', 'Emergency Access')], help_text='Nivel de acceso utilizado', max_length=20)),
                ('is_own_institution', models.BooleanField(default=True, help_text='True si es institución propia del médico')),
                ('is_cross_institution', models.BooleanField(default=False, help_text='True si es cross-institution access')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Dirección IP del acceso', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User Agent del navegador')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Cuándo ocurrió el acceso')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información adicional en formato JSON')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalMercantilP2CTransaction',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto de la Transacción')),
                ('currency', models.CharField(default='VES', max_length=3, verbose_name='Moneda')),
                ('qr_code_data', models.TextField(help_text='Contenido completo del QR generado por Mercantil', verbose_name='Datos del Código QR')),
                ('qr_image_url', models.URLField(blank=True, help_text='URL de la imagen del QR generada (opcional)', max_length=500, null=True, verbose_name='URL de Imagen QR')),
                ('mercantil_transaction_id', models.CharField(blank=True, db_index=True, help_text='ID único retornado por API de Mercantil', max_length=100, null=True, verbose_name='ID Transacción Mercantil')),
                ('merchant_order_id', models.CharField(db_index=True, help_text='ID único de nuestra orden para rastreo', max_length=100, verbose_name='ID Orden Comerciante')),
                ('status', models.CharField(choices=[('generated', 'QR Generado'), ('pending', 'Pendiente de Pago'), ('confirmed', 'Pago Confirmado'), ('expired', 'QR Expirado'), ('cancelled', 'Cancelado'), ('failed', 'Fallido')], default='generated', max_length=20, verbose_name='Estado de Transacción')),
                ('generated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Generación QR')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Expiración QR')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Confirmación de Pago')),
                ('gateway_response_raw', models.JSONField(blank=True, help_text='Respuesta completa de API Mercantil', null=True, verbose_name='Respuesta Raw Gateway')),
                ('callback_data', models.JSONField(blank=True, help_text='Datos recibidos en webhook de confirmación', null=True, verbose_name='Datos de Callback')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Transacción P2C Mercantil',
                'verbose_name_plural': 'historical Transacciones P2C Mercantil',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='InstitutionPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('full_access', 'Acceso Completo'), ('emergency_access', 'Acceso de Emergencia')], default='full_access', max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Para emergency access (24h default)', null=True)),
                ('is_own_institution', models.BooleanField(default=True, help_text="True si el médico 'posee' esta institución")),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-granted_at'],
            },
        ),
        migrations.CreateModel(
            name='MercantilP2CConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Client ID Mercantil')),
                ('secret_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Secret Key Mercantil')),
                ('webhook_secret', models.CharField(blank=True, max_length=100, null=True, verbose_name='Webhook Secret')),
                ('is_test_mode', models.BooleanField(default=True, help_text='Activar modo sandbox de Mercantil', verbose_name='Modo de Pruebas (Sandbox)')),
                ('qr_expiration_minutes', models.PositiveIntegerField(default=15, help_text='Tiempo en minutos antes de que el QR expire', verbose_name='Tiempo de Expiración QR (minutos)')),
                ('max_amount', models.DecimalField(decimal_places=2, default=Decimal('1000000.00'), max_digits=12, verbose_name='Monto Máximo por Transacción')),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12, verbose_name='Monto Mínimo por Transacción')),
                ('webhook_url', models.URLField(blank=True, help_text='URL donde Mercantil enviará confirmaciones de pago', max_length=500, null=True, verbose_name='URL de Webhook')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración P2C Mercantil',
                'verbose_name_plural': 'Configuraciones P2C Mercantil',
            },
        ),
        migrations.CreateModel(
            name='MercantilP2CTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto de la Transacción')),
                ('currency', models.CharField(default='VES', max_length=3, verbose_name='Moneda')),
                ('qr_code_data', models.TextField(help_text='Contenido completo del QR generado por Mercantil', verbose_name='Datos del Código QR')),
                ('qr_image_url', models.URLField(blank=True, help_text='URL de la imagen del QR generada (opcional)', max_length=500, null=True, verbose_name='URL de Imagen QR')),
                ('mercantil_transaction_id', models.CharField(blank=True, help_text='ID único retornado por API de Mercantil', max_length=100, null=True, unique=True, verbose_name='ID Transacción Mercantil')),
                ('merchant_order_id', models.CharField(help_text='ID único de nuestra orden para rastreo', max_length=100, unique=True, verbose_name='ID Orden Comerciante')),
                ('status', models.CharField(choices=[('generated', 'QR Generado'), ('pending', 'Pendiente de Pago'), ('confirmed', 'Pago Confirmado'), ('expired', 'QR Expirado'), ('cancelled', 'Cancelado'), ('failed', 'Fallido')], default='generated', max_length=20, verbose_name='Estado de Transacción')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación QR')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Expiración QR')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Confirmación de Pago')),
                ('gateway_response_raw', models.JSONField(blank=True, help_text='Respuesta completa de API Mercantil', null=True, verbose_name='Respuesta Raw Gateway')),
                ('callback_data', models.JSONField(blank=True, help_text='Datos recibidos en webhook de confirmación', null=True, verbose_name='Datos de Callback')),
            ],
            options={
                'verbose_name': 'Transacción P2C Mercantil',
                'verbose_name_plural': 'Transacciones P2C Mercantil',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='medicalreport',
            options={'verbose_name': 'Informe Médico', 'verbose_name_plural': 'Informes Médicos'},
        ),
        migrations.AddField(
            model_name='chargeorder',
            name='doctor',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge_orders', to='core.doctoroperator', verbose_name='Médico emisor de cobro'),
        ),
        migrations.AddField(
            model_name='doctoroperator',
            name='active_institution',
            field=models.ForeignKey(blank=True, help_text='La institución preferida del doctor. Se usa por defecto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_doctors', to='core.institutionsettings', verbose_name='Institución Activa (Predeterminada)'),
        ),
        migrations.AddField(
            model_name='historicalchargeorder',
            name='doctor',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.doctoroperator', verbose_name='Médico emisor de cobro'),
        ),
        migrations.AddField(
            model_name='historicaldoctoroperator',
            name='active_institution',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='La institución preferida del doctor. Se usa por defecto.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.institutionsettings', verbose_name='Institución Activa (Predeterminada)'),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='doctor',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.doctoroperator', verbose_name='Médico asociado al pago'),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='doctor',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_documents', to='core.doctoroperator', verbose_name='Médico asociado'),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='institution',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_documents', to='core.institutionsettings', verbose_name='Sede asociada'),
        ),
        migrations.AddField(
            model_name='medicalreferral',
            name='doctor',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_referrals', to='core.doctoroperator', verbose_name='Médico que emite la referencia'),
        ),
        migrations.AddField(
            model_name='medicalreferral',
            name='institution',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_referrals', to='core.institutionsettings', verbose_name='Sede donde se emitió'),
        ),
        migrations.AddField(
            model_name='medicalreferral',
            name='patient',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='core.patient', verbose_name='Paciente referido'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='doctor',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_reports', to='core.doctoroperator', verbose_name='Médico asociado'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='institution',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_reports', to='core.institutionsettings', verbose_name='Sede asociada'),
        ),
        migrations.AddField(
            model_name='payment',
            name='doctor',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.doctoroperator', verbose_name='Médico asociado al pago'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='doctor',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments', to='core.doctoroperator', verbose_name='Médico asociado'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='institution',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments', to='core.institutionsettings', verbose_name='Sede asociada'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='patient',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='core.patient', verbose_name='Paciente asociado'),
        ),
        migrations.AlterField(
            model_name='medicalreferral',
            name='referred_to_doctor',
            field=models.ForeignKey(blank=True, help_text='Médico interno registrado en MedOpz (DESTINO)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_referrals', to='core.doctoroperator'),
        ),
        migrations.AlterField(
            model_name='medicalreferral',
            name='referred_to_external',
            field=models.CharField(blank=True, help_text='Nombre del doctor o clínica externa (si no está en MedOpz) (DESTINO)', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='chargeorder',
            index=models.Index(fields=['doctor', 'status'], name='core_charge_doctor__a9403b_idx'),
        ),
        migrations.AddIndex(
            model_name='medicaldocument',
            index=models.Index(fields=['doctor', 'category'], name='core_medica_doctor__e6ec1a_idx'),
        ),
        migrations.AddIndex(
            model_name='medicaldocument',
            index=models.Index(fields=['institution', 'category'], name='core_medica_institu_0504a9_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalreferral',
            index=models.Index(fields=['doctor', 'issued_at'], name='core_medica_doctor__c3c202_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalreferral',
            index=models.Index(fields=['institution', 'issued_at'], name='core_medica_institu_75befd_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalreferral',
            index=models.Index(fields=['patient', 'issued_at'], name='core_medica_patient_927339_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalreferral',
            index=models.Index(fields=['referred_to_doctor', 'status'], name='core_medica_referre_4c9aa0_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalreport',
            index=models.Index(fields=['doctor', 'created_at'], name='core_medica_doctor__ca68b4_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalreport',
            index=models.Index(fields=['institution', 'created_at'], name='core_medica_institu_22469b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['doctor', 'status'], name='core_paymen_doctor__ae623d_idx'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['doctor', 'status'], name='core_treatm_doctor__ebbaa8_idx'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['patient', 'status'], name='core_treatm_patient_c69a30_idx'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['institution', 'status'], name='core_treatm_institu_62df55_idx'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.institutionsettings'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmercantilp2ctransaction',
            name='charge_order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.chargeorder', verbose_name='Orden de Cobro Asociada'),
        ),
        migrations.AddField(
            model_name='historicalmercantilp2ctransaction',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmercantilp2ctransaction',
            name='institution',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.institutionsettings', verbose_name='Institución'),
        ),
        migrations.AddField(
            model_name='historicalmercantilp2ctransaction',
            name='payment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.payment', verbose_name='Pago Confirmado'),
        ),
        migrations.AddField(
            model_name='institutionpermission',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='institutionpermission',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='core.institutionsettings'),
        ),
        migrations.AddField(
            model_name='institutionpermission',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institution_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mercantilp2cconfig',
            name='institution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='p2c_config', to='core.institutionsettings', verbose_name='Institución'),
        ),
        migrations.AddField(
            model_name='mercantilp2ctransaction',
            name='charge_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2c_transactions', to='core.chargeorder', verbose_name='Orden de Cobro Asociada'),
        ),
        migrations.AddField(
            model_name='mercantilp2ctransaction',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2c_transactions', to='core.institutionsettings', verbose_name='Institución'),
        ),
        migrations.AddField(
            model_name='mercantilp2ctransaction',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2c_transactions', to='core.payment', verbose_name='Pago Confirmado'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='core_auditl_user_id_7b678c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['institution', 'timestamp'], name='core_auditl_institu_ad7348_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'timestamp'], name='core_auditl_action_096de0_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['is_cross_institution'], name='core_auditl_is_cros_f86718_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='institutionpermission',
            unique_together={('user', 'institution')},
        ),
        migrations.AddIndex(
            model_name='mercantilp2ctransaction',
            index=models.Index(fields=['institution', 'status'], name='core_mercan_institu_d9f5e0_idx'),
        ),
        migrations.AddIndex(
            model_name='mercantilp2ctransaction',
            index=models.Index(fields=['mercantil_transaction_id'], name='core_mercan_mercant_7b24e2_idx'),
        ),
        migrations.AddIndex(
            model_name='mercantilp2ctransaction',
            index=models.Index(fields=['merchant_order_id'], name='core_mercan_merchan_4c5f5e_idx'),
        ),
        migrations.AddIndex(
            model_name='mercantilp2ctransaction',
            index=models.Index(fields=['status', 'generated_at'], name='core_mercan_status_125011_idx'),
        ),
    ]
