# Generated by Django 5.2.7 on 2026-05-16 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email del médico invitado', max_length=254)),
                ('token', models.CharField(editable=False, help_text='Token criptográfico único de 64 caracteres', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False, help_text='Si True, la invitación ya fue canjeada')),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_invitations', to='core.institutionsettings')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('specialty', models.ForeignKey(blank=True, help_text='Especialidad sugerida (opcional, puede confirmar/elegir en activación)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='core.specialty')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_invitation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invitación de Médico',
                'verbose_name_plural': 'Invitaciones de Médicos',
                'ordering': ['-created_at'],
            },
        ),
    ]
