# Generated by Django 5.2.7 on 2025-10-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_patient_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatient',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo electrónico'),
        ),
    ]
