# Generated by Django 5.2.7 on 2026-05-17 19:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_doctorinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_file', models.FileField(blank=True, help_text='Documento oficial emitido por el MPPS', null=True, upload_to='doctor_licenses/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Licencia Sanitaria (PDF)')),
                ('license_expiry_date', models.DateField(blank=True, help_text='Fecha de expiry de la licencia sanitaria', null=True, verbose_name='Fecha de vencimiento de licencia')),
                ('colegiado_card_file', models.FileField(blank=True, help_text='Documento que acredita membresía vigente', null=True, upload_to='doctor_credentials/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Carné de Colegio de Médicos')),
                ('university_diploma_file', models.FileField(blank=True, help_text='Título universitario de médico cirujano', null=True, upload_to='doctor_education/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Diploma de Grado (PDF)')),
                ('additional_docs', models.JSONField(blank=True, help_text='Lista de URLs de documentos adicionales cargados', null=True, verbose_name='Documentos adicionales')),
                ('is_verified_by_admin', models.BooleanField(default=False, help_text='Solo los administradores pueden marcar como verificado', verbose_name='Verificado por Administrador')),
                ('verification_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Verificación')),
                ('verification_notes', models.TextField(blank=True, help_text='Comentarios del administrador sobre la verificación', null=True, verbose_name='Notas de Verificación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Licencia y Credenciales del Médico',
                'verbose_name_plural': 'Licencias y Credenciales de Médicos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='doctorinvitation',
            name='colegiado_number',
            field=models.CharField(default='PENDING', help_text='Verificación ante el Colegio de Médicos de Venezuela', max_length=50, verbose_name='Número de Colegiado MPPS'),
        ),
        migrations.AddField(
            model_name='doctorinvitation',
            name='full_name',
            field=models.CharField(default='PENDING', help_text='Nombre completo según documento de identidad', max_length=255),
        ),
        migrations.AddField(
            model_name='doctorinvitation',
            name='license_number',
            field=models.CharField(default='PENDING', help_text='Autorización sanitaria vigente del MPPS', max_length=50, verbose_name='Licencia Sanitaria MPPS'),
        ),
        migrations.AddField(
            model_name='doctorinvitation',
            name='national_id',
            field=models.CharField(default='V-00000000', help_text='Cédula de Identidad (V-xxxxxxxx)', max_length=12, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(12)]),
        ),
        migrations.AlterField(
            model_name='doctorinvitation',
            name='email',
            field=models.EmailField(help_text='Email personal del médico invitado', max_length=254),
        ),
        migrations.AddIndex(
            model_name='doctorinvitation',
            index=models.Index(fields=['national_id'], name='core_doctor_nationa_f77969_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorinvitation',
            index=models.Index(fields=['colegiado_number'], name='core_doctor_colegia_f2e966_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorinvitation',
            index=models.Index(fields=['email'], name='core_doctor_email_1086db_idx'),
        ),
        migrations.AddField(
            model_name='doctorlicense',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license_info', to='core.doctoroperator', verbose_name='Médico'),
        ),
        migrations.AddField(
            model_name='doctorlicense',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_doctor_licenses', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por'),
        ),
    ]
