# Generated by Django 5.2.7 on 2026-05-17 19:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_enhance_doctor_invitation_and_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoroperator',
            name='agregado_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Número de colegiado / ID de ejercicio'),
        ),
        migrations.AddField(
            model_name='doctoroperator',
            name='birth_country',
            field=models.CharField(default='Venezuela', help_text='País emisor del documento de identidad', max_length=100, verbose_name='País de nacimiento'),
        ),
        migrations.AddField(
            model_name='doctoroperator',
            name='birthdate',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento (dd/mm/aaaa)', null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='doctoroperator',
            name='is_active_license',
            field=models.BooleanField(default=True, help_text='Designa si la licencia sanitaria está vigente', verbose_name='Licencia activa'),
        ),
        migrations.AddField(
            model_name='doctoroperator',
            name='license_expiry_date',
            field=models.DateField(blank=True, help_text='Fecha de expiry de la licencia sanitaria MPPS', null=True, verbose_name='Fecha de vencimiento de licencia'),
        ),
        migrations.AddField(
            model_name='doctoroperator',
            name='national_id',
            field=models.CharField(default='V-00000000', help_text='Cédula de Identidad (V-xxxxxxxxx)', max_length=12, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(12)]),
        ),
        migrations.AddField(
            model_name='doctoroperator',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Comentarios del administrador sobre la verificación MPPS', null=True, verbose_name='Notas de verificación'),
        ),
        migrations.AddField(
            model_name='historicaldoctoroperator',
            name='agregado_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Número de colegiado / ID de ejercicio'),
        ),
        migrations.AddField(
            model_name='historicaldoctoroperator',
            name='birth_country',
            field=models.CharField(default='Venezuela', help_text='País emisor del documento de identidad', max_length=100, verbose_name='País de nacimiento'),
        ),
        migrations.AddField(
            model_name='historicaldoctoroperator',
            name='birthdate',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento (dd/mm/aaaa)', null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='historicaldoctoroperator',
            name='is_active_license',
            field=models.BooleanField(default=True, help_text='Designa si la licencia sanitaria está vigente', verbose_name='Licencia activa'),
        ),
        migrations.AddField(
            model_name='historicaldoctoroperator',
            name='license_expiry_date',
            field=models.DateField(blank=True, help_text='Fecha de expiry de la licencia sanitaria MPPS', null=True, verbose_name='Fecha de vencimiento de licencia'),
        ),
        migrations.AddField(
            model_name='historicaldoctoroperator',
            name='national_id',
            field=models.CharField(default='V-00000000', help_text='Cédula de Identidad (V-xxxxxxxxx)', max_length=12, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(12)]),
        ),
        migrations.AddField(
            model_name='historicaldoctoroperator',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Comentarios del administrador sobre la verificación MPPS', null=True, verbose_name='Notas de verificación'),
        ),
    ]
