# Generated by Django 5.2.7 on 2026-02-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chargeorder_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationcatalog',
            name='atc_code',
            field=models.CharField(blank=True, help_text='Código ATC (Clasificación Anatómica Terapéutica)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='medicationcatalog',
            name='concentration_detail',
            field=models.JSONField(blank=True, default=list, help_text='Concentración detallada para medicamentos combinados'),
        ),
        migrations.AddField(
            model_name='medicationcatalog',
            name='inhrr_code',
            field=models.CharField(blank=True, help_text='Código de registro sanitario del INHRR (ej: E.F.42.246)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicationcatalog',
            name='inhrr_status',
            field=models.CharField(choices=[('VIGENTE', 'Vigente'), ('CANCELADO', 'Cancelado'), ('SUSPENDIDO', 'Suspendido'), ('VENCIDO', 'Vencido')], default='VIGENTE', help_text='Estatus del medicamento según el INHRR', max_length=20),
        ),
        migrations.AddField(
            model_name='medicationcatalog',
            name='last_scraped_at',
            field=models.DateTimeField(blank=True, help_text='Fecha del último scraping', null=True),
        ),
        migrations.AddField(
            model_name='medicationcatalog',
            name='presentation_size',
            field=models.CharField(blank=True, help_text='Tamaño de la presentación (ej: Jarabe x 60 ml, Tableta x 30)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicationcatalog',
            name='search_vector',
            field=models.TextField(blank=True, help_text='Vector de búsqueda para full-text search'),
        ),
        migrations.AddField(
            model_name='medicationcatalog',
            name='source',
            field=models.CharField(default='INHRR', help_text='Fuente de los datos (INHRR, MANUAL, etc.)', max_length=20),
        ),
        migrations.AddField(
            model_name='medicationcatalog',
            name='therapeutic_action',
            field=models.TextField(blank=True, help_text='Acción terapéutica (ej: Antihistamínico, Antiinflamatorio)', null=True),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='medicaltestcatalog',
            name='name',
            field=models.CharField(help_text='Nombre del examen', max_length=255),
        ),
        migrations.AlterField(
            model_name='medicationcatalog',
            name='concentration',
            field=models.CharField(help_text='Concentración del medicamento (ej: 500 mg, 5mg/60mg por 5ml)', max_length=200),
        ),
        migrations.AlterField(
            model_name='medicationcatalog',
            name='generic_name',
            field=models.CharField(blank=True, help_text='Principio activo (ej: Acetaminofén, Loratadina + Pseudoefedrina)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='medicationcatalog',
            name='name',
            field=models.CharField(help_text='Nombre comercial o genérico principal (ej: Atamel, Loratadina + Pseudoefedrina)', max_length=500),
        ),
        migrations.AlterField(
            model_name='medicationcatalog',
            name='presentation',
            field=models.CharField(choices=[('tablet', 'Tableta'), ('capsule', 'Cápsula'), ('syrup', 'Jarabe'), ('drop', 'Gotas'), ('injection', 'Inyectable'), ('cream', 'Crema'), ('gel', 'Gel'), ('patch', 'Parche'), ('spray', 'Spray'), ('other', 'Otro'), ('tablet_coated', 'Tableta Recubierta'), ('suspension', 'Suspensión'), ('solution', 'Solución'), ('ointment', 'Ungüento'), ('inhaler', 'Inhalador'), ('suppository', 'Supositorio'), ('powder', 'Polvo'), ('granules', 'Gránulos'), ('mouthwash', 'Enjuague')], help_text='Forma farmacéutica (tableta, jarabe, cápsula, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='medicationcatalog',
            name='route',
            field=models.CharField(choices=[('oral', 'Oral'), ('intravenous', 'Intravenosa (IV)'), ('intramuscular', 'Intramuscular (IM)'), ('subcutaneous', 'Subcutánea (SC)'), ('topical', 'Tópica'), ('sublingual', 'Sublingual'), ('inhalation', 'Inhalación'), ('rectal', 'Rectal'), ('ophthalmic', 'Oftálmica'), ('otic', 'Ótica'), ('nasal', 'Nasal'), ('other', 'Otro')], help_text='Vía de administración', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicationcatalog',
            name='unit',
            field=models.CharField(choices=[('mg', 'Miligramos (mg)'), ('ml', 'Mililitros (ml)'), ('g', 'Gramos (g)'), ('mcg', 'Microgramos (mcg)'), ('L', 'Litros (L)'), ('tablet_unit', 'Tableta(s)'), ('capsule_unit', 'Cápsula(s)'), ('drop_unit', 'Gota(s)'), ('puff_unit', 'Puff(s)'), ('unit', 'Unidad(es)'), ('IU', 'Unidades Internacionales (IU)'), ('mEq', 'Miliequivalentes (mEq)'), ('percent', 'Porcentaje (%)'), ('patch', 'Parche'), ('other', 'Otro')], help_text='Unidad de medida de la concentración', max_length=20),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='route',
            field=models.CharField(choices=[('oral', 'Oral'), ('intravenous', 'Intravenosa (IV)'), ('intramuscular', 'Intramuscular (IM)'), ('subcutaneous', 'Subcutánea (SC)'), ('topical', 'Tópica'), ('sublingual', 'Sublingual'), ('inhalation', 'Inhalación'), ('rectal', 'Rectal'), ('ophthalmic', 'Oftálmica'), ('otic', 'Ótica'), ('nasal', 'Nasal'), ('other', 'Otro')], default='oral', max_length=20),
        ),
        migrations.AlterField(
            model_name='prescriptioncomponent',
            name='unit',
            field=models.CharField(choices=[('mg', 'Miligramos (mg)'), ('ml', 'Mililitros (ml)'), ('g', 'Gramos (g)'), ('mcg', 'Microgramos (mcg)'), ('L', 'Litros (L)'), ('tablet_unit', 'Tableta(s)'), ('capsule_unit', 'Cápsula(s)'), ('drop_unit', 'Gota(s)'), ('puff_unit', 'Puff(s)'), ('unit', 'Unidad(es)'), ('IU', 'Unidades Internacionales (IU)'), ('mEq', 'Miliequivalentes (mEq)'), ('percent', 'Porcentaje (%)'), ('patch', 'Parche'), ('other', 'Otro')], default='mg', max_length=20),
        ),
        migrations.AddIndex(
            model_name='medicationcatalog',
            index=models.Index(fields=['name'], name='core_medica_name_87f1b8_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationcatalog',
            index=models.Index(fields=['generic_name'], name='core_medica_generic_02bf74_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationcatalog',
            index=models.Index(fields=['presentation'], name='core_medica_present_61cbb5_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationcatalog',
            index=models.Index(fields=['route'], name='core_medica_route_a62ca1_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationcatalog',
            index=models.Index(fields=['institution'], name='core_medica_institu_2daa0f_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationcatalog',
            index=models.Index(fields=['inhrr_status'], name='core_medica_inhrr_s_5e7a4f_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationcatalog',
            index=models.Index(fields=['is_active'], name='core_medica_is_acti_37e36a_idx'),
        ),
    ]
