# Generated by Django 5.2.7 on 2026-05-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_doctoroperator_mpps_compliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorpaymentconfig',
            name='bank_transfer_enabled',
            field=models.BooleanField(default=False, help_text='Habilitar pagos vía transferencia directa', verbose_name='Transferencia bancaria habilitada'),
        ),
        migrations.AddField(
            model_name='doctorpaymentconfig',
            name='binance_crypto_wallet_address',
            field=models.CharField(blank=True, help_text='Dirección de wallet Binance para recibir USDT en red TRC20', max_length=200, verbose_name='Binance Crypto Wallet (USDT-TRC20)'),
        ),
        migrations.AddField(
            model_name='doctorpaymentconfig',
            name='binance_network',
            field=models.CharField(blank=True, default='TRC20', help_text='Red blockchain para depósitos crypto (TRC20, ERC20, BEP20)', max_length=20, verbose_name='Binance Network'),
        ),
        migrations.AddField(
            model_name='doctorpaymentconfig',
            name='crypto_enabled',
            field=models.BooleanField(default=False, help_text='Habilitar pagos en USDT (Binance)', verbose_name='Crypto USDT habilitado'),
        ),
        migrations.AddField(
            model_name='doctorpaymentconfig',
            name='payment_mobile_enabled',
            field=models.BooleanField(default=True, help_text='Habilitar pagos vía Pago Móvil bancario', verbose_name='Pago Móvil habilitado'),
        ),
    ]
