# Generated by Django 5.2.7 on 2026-02-22 02:56

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_medication_catalog_inhrr_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaltest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('collected', 'Muestra Recolectada'), ('in_process', 'En Proceso'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicaltest',
            name='test_type',
            field=models.CharField(choices=[('hemogram', 'Hemograma Completo'), ('hemoglobin', 'Hemoglobina / Hematocrito'), ('platelets', 'Conteo de Plaquetas'), ('reticulocytes', 'Reticulocitos'), ('coag_pt', 'Tiempos de Coagulación (PT/PTT/INR)'), ('blood_type', 'Grupo Sanguíneo y Rh'), ('peripheral_smear', 'Frotis de Sangre Periférica'), ('bone_marrow', 'Aspirado de Médula Ósea'), ('glucose', 'Glucemia'), ('glucose_2h', 'Glucemia Post-Prandial (2h)'), ('glycated_hgb', 'Hemoglobina Glicosilada (HbA1c)'), ('curva_glucosa', 'Curva de Tolerancia a Glucosa'), ('lipid_profile', 'Perfil Lipídico'), ('renal_panel', 'Perfil Renal (BUN/Cr)'), ('liver_panel', 'Perfil Hepático'), ('electrolytes', 'Electrolitos Séricos'), ('thyroid_panel', 'Perfil Tiroideo (TSH/T3/T4)'), ('bone_profile', 'Perfil Óseo (Ca/P/FA)'), ('cardiac_enzymes', 'Enzimas Cardíacas (Troponina/CK)'), ('tumor_markers', 'Marcadores Tumorales'), ('iron_studies', 'Perfil de Hierro (Ferritina)'), ('vitamin_d', 'Vitamina D (25-OH)'), ('vitamin_b12', 'Vitamina B12'), ('folate', 'Ácido Fólico'), ('amylase', 'Amilasa / Lipasa'), ('uric_acid', 'Ácido Úrico'), ('protein_total', 'Proteínas Totales / Albúmina'), ('bilirubin', 'Bilirrubinas'), ('creatinine_clearance', 'Depuración de Creatinina'), ('urinalysis', 'Uroanálisis Completo'), ('urine_culture', 'Urocultivo'), ('urine_24h', 'Orina 24 Horas'), ('urine_protein', 'Proteinuria 24h'), ('urine_microalbumin', 'Microalbuminuria'), ('stool_routine', 'Examen de Heces'), ('stool_occult', 'Sangre Oculta en Heces'), ('stool_parasites', 'Parasitológico en Heces'), ('stool_culture', 'Coprocultivo'), ('stool_elisa', 'Antígeno en Heces (ELISA)'), ('blood_culture', 'Hemocultivo'), ('wound_culture', 'Cultivo de Herida'), ('throat_culture', 'Exudado Faríngeo'), ('sputum_culture', 'Cultivo de Esputo'), ('csf_analysis', 'Líquido Cefalorraquídeo'), ('synovial_fluid', 'Líquido Sinovial'), ('pleural_fluid', 'Líquido Pleural'), ('ascitic_fluid', 'Líquido Ascítico'), ('covid_pcr', 'PCR COVID-19'), ('covid_antigen', 'Antígeno COVID-19'), ('covid_antibodies', 'Anticuerpos COVID-19'), ('viral_panel', 'Panel Viral'), ('bacterial_panel', 'Panel Bacteriano'), ('fungus_culture', 'Cultivo de Hongos'), ('mycobacteria', 'Micobacterias (BK)'), ('hiv_test', 'Prueba VIH (ELISA/Rápida)'), ('hepatitis_panel', 'Panel Hepatitis (A/B/C)'), ('autoimmune_panel', 'Panel Autoinmune (ANA/ENA)'), ('rheumatoid_factor', 'Factor Reumatoideo'), ('anti_ccp', 'Anti-CCP'), ('crp', 'Proteína C Reactiva (PCR)'), ('esr', 'Velocidad de Sedimentación (VSG)'), ('allergy_panel', 'Panel Alérgico (IgE)'), ('immunoglobulins', 'Inmunoglobulinas (IgG/IgA/IgM)'), ('complement', 'Complemento (C3/C4)'), ('cryoglobulins', 'Cryoglobulinas'), ('cortisol', 'Cortisol'), ('acth', 'ACTH'), ('growth_hormone', 'Hormona de Crecimiento'), ('prolactin', 'Prolactina'), ('lh_fsh', 'LH / FSH'), ('testosterone', 'Testosterona'), ('estradiol', 'Estradiol'), ('progesterone', 'Progesterona'), ('dhea', 'DHEA-S'), ('insulin', 'Insulina'), ('peptide_c', 'Péptido C'), ('xray_chest', 'Radiografía de Tórax'), ('xray_abdomen', 'Radiografía de Abdomen'), ('xray_bone', 'Radiografía Ósea'), ('xray_spine_cervical', 'Radiografía Cervical'), ('xray_spine_lumbar', 'Radiografía Lumbar'), ('xray_spine_dorsal', 'Radiografía Dorsal'), ('xray_pelvis', 'Radiografía de Pelvis'), ('xray_skull', 'Radiografía de Cráneo'), ('xray_sinus', 'Radiografía de Senos Paranasales'), ('xray_extremity', 'Radiografía de Extremidades'), ('xray_dental', 'Radiografía Dental'), ('xray_contrast', 'Radiografía con Contraste'), ('ultrasound_abdo', 'Ecografía Abdominal'), ('ultrasound_pelvic', 'Ecografía Pélvica'), ('ultrasound_thyroid', 'Ecografía Tiroidea'), ('ultrasound_obstetric', 'Ecografía Obstétrica'), ('ultrasound_doppler', 'Doppler Vascular'), ('ultrasound_cardiac', 'Ecocardiograma'), ('ultrasound_breast', 'Ecografía Mamaria'), ('ultrasound_prostate', 'Ecografía Prostática'), ('ultrasound_testicular', 'Ecografía Testicular'), ('ultrasound_soft_tissue', 'Ecografía de Partes Blandas'), ('ultrasound_joint', 'Ecografía Articular'), ('ct_head', 'TC de Cráneo'), ('ct_brain_angio', 'TC Cerebral con Angio'), ('ct_abdomen', 'TC Abdominal'), ('ct_chest', 'TC de Tórax'), ('ct_spine', 'TC de Columna'), ('ct_pelvis', 'TC de Pelvis'), ('ct_neck', 'TC de Cuello'), ('ct_sinus', 'TC de Senos Paranasales'), ('ct_cardiac', 'TC Cardíaca'), ('ct_angio', 'TC Angiografía'), ('mri_brain', 'RM Cerebral'), ('mri_spine', 'RM de Columna'), ('mri_joint', 'RM Articular'), ('mri_abdomen', 'RM Abdominal'), ('mri_pelvis', 'RM Pélvica'), ('mri_cardiac', 'RM Cardíaca'), ('mri_angio', 'RM Angiografía'), ('mri_prostate', 'RM Prostática'), ('mri_breast', 'RM Mamaria'), ('mammography', 'Mamografía'), ('mammography_3d', 'Tomosíntesis Mamaria'), ('densitometry', 'Densitometría Ósea'), ('fluoroscopy', 'Fluoroscopía'), ('angiography', 'Angiografía'), ('hysterosalpingography', 'Histerosalpingografía'), ('urography', 'Urografía'), ('cholangiography', 'Colangiografía'), ('pet_ct', 'PET-CT'), ('bone_scan', 'Gammagrafía Ósea'), ('thyroid_scan', 'Gammagrafía Tiroidea'), ('lung_scan', 'Gammagrafía Pulmonar'), ('renal_scan', 'Gammagrafía Renal'), ('ecg_12lead', 'ECG 12 Derivaciones'), ('ecg_holter', 'Holter 24h'), ('ecg_event', 'Monitoreo de Eventos'), ('echo_cardiac', 'Ecocardiograma Transtorácico'), ('echo_transesophageal', 'Ecocardiograma Transesofágico'), ('stress_test', 'Prueba de Esfuerzo'), ('stress_echo', 'Eco-Estrés'), ('ambulatory_bp', 'MAPA (Presión 24h)'), ('tilt_test', 'Prueba de Mesa Inclinada'), ('abi', 'Índice Tobillo-Brazo'), ('spirometry', 'Espirometría'), ('spirometry_post', 'Espirometría Post-Broncodilatador'), ('plethysmography', 'Pletismografía'), ('pulse_oximetry', 'Oximetría de Pulso'), ('sleep_study', 'Polisomnografía'), ('capnography', 'Capnografía'), ('diffusion_capacity', 'Capacidad de Difusión'), ('eeg', 'Electroencefalograma'), ('eeg_video', 'Video-EEG'), ('emg', 'Electromiografía'), ('nerve_conduction', 'Conducción Nerviosa'), ('evoked_potentials', 'Potenciales Evocados'), ('vep', 'Potenciales Evocados Visuales'), ('baep', 'Potenciales Evocados Auditivos'), ('sep', 'Potenciales Evocados Somatosensoriales'), ('endoscopy_ugi', 'Endoscopía Alta (EGD)'), ('colonoscopy', 'Colonoscopía'), ('colonoscopy_virtual', 'Colonoscopía Virtual'), ('bronchoscopy', 'Broncoscopía'), ('cystoscopy', 'Cistoscopía'), ('gastroscopy', 'Gastroscopía'), ('sigmoidoscopy', 'Sigmoidoscopía'), ('capsule_endoscopy', 'Cápsula Endoscópica'), ('ercp', 'CPRE'), ('thoracoscopy', 'Toracoscopía'), ('laparoscopy', 'Laparoscopía Diagnóstica'), ('arthroscopy', 'Artroscopía'), ('visual_acuity', 'Agudeza Visual'), ('tonometry', 'Tonometría'), ('oct_eye', 'OCT Ocular'), ('fundoscopy', 'Fondo de Ojo'), ('slit_lamp', 'Lámpara de Hendidura'), ('visual_field', 'Campo Visual'), ('retinography', 'Retinografía'), ('corneal_topography', 'Topografía Corneal'), ('pachymetry', 'Paquimetría'), ('biometry', 'Biometría Ocular'), ('color_vision', 'Test de Visión de Colores'), ('audiometry', 'Audiometría'), ('audiometry_speech', 'Audiometría con Logoaudiometría'), ('tympanometry', 'Timpanometría'), ('otoacoustic', 'Emisiones Otoacústicas'), ('bera', 'BERA (Potenciales Auditivos)'), ('nasendoscopy', 'Nasofibroscopía'), ('laryngoscopy', 'Laringoscopía'), ('vestibular_test', 'Pruebas Vestibulares'), ('papanicolaou', 'Papanicolaou'), ('colposcopy', 'Colposcopía'), ('hysteroscopy', 'Histeroscopía'), ('amniocentesis', 'Amniocentesis'), ('chorionic_villus', 'Biopsia de Vellosidades Coriónicas'), ('nfetal_monitoring', 'Monitoreo Fetal'), ('biophysical_profile', 'Perfil Biofísico Fetal'), ('semen_analysis', 'Espermatograma'), ('biopsy', 'Biopsia'), ('biopsy_skin', 'Biopsia de Piel'), ('biopsy_bone', 'Biopsia Ósea'), ('biopsy_liver', 'Biopsia Hepática'), ('biopsy_kidney', 'Biopsia Renal'), ('biopsy_lung', 'Biopsia Pulmonar'), ('biopsy_prostate', 'Biopsia de Próstata'), ('biopsy_breast', 'Biopsia de Mama'), ('puncture_lumbar', 'Punción Lumbar'), ('thoracentesis', 'Toracocentesis'), ('paracentesis', 'Paracentesis'), ('arthrocentesis', 'Artrocentesis'), ('bonemarrow_biopsy', 'Biopsia de Médula Ósea'), ('genetic_test', 'Prueba Genética'), ('karyotype', 'Cariotipo'), ('fish', 'FISH'), ('pcr_genetic', 'PCR Genética'), ('newborn_screening', 'Tamizaje Neonatal'), ('paternity_test', 'Prueba de Paternidad'), ('pharmacogenomics', 'Farmacogenómica'), ('drug_screen', 'Tamizaje de Drogas'), ('alcohol_test', 'Prueba de Alcohol'), ('heavy_metals', 'Metales Pesados'), ('therapeutic_drug', 'Monitoreo de Fármacos'), ('pregnancy_test', 'Prueba de Embarazo'), ('sweat_test', 'Test del Sudor'), ('mantoux', 'Prueba de Mantoux (PPD)'), ('allergy_skin', 'Pruebas Cutáneas de Alergia'), ('patch_test', 'Test de Parche'), ('other', 'Otro Examen')], max_length=50),
        ),
        migrations.AlterField(
            model_name='medicaltest',
            name='urgency',
            field=models.CharField(choices=[('routine', 'Rutina'), ('priority', 'Prioridad'), ('urgent', 'Urgente'), ('stat', 'STAT (Inmediato)')], default='routine', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicaltestcatalog',
            name='category',
            field=models.CharField(choices=[('lab_hematology', 'Laboratorio → Hematología'), ('lab_biochemistry', 'Laboratorio → Bioquímica'), ('lab_immunology', 'Laboratorio → Inmunología'), ('lab_microbiology', 'Laboratorio → Microbiología'), ('lab_parasitology', 'Laboratorio → Parasitología'), ('lab_urinalysis', 'Laboratorio → Uroanálisis'), ('lab_endocrinology', 'Laboratorio → Endocrinología'), ('lab_toxicology', 'Laboratorio → Toxicología'), ('lab_coagulation', 'Laboratorio → Coagulación'), ('lab_special', 'Laboratorio → Pruebas Especiales'), ('img_xray', 'Imagenología → Rayos X'), ('img_ultrasound', 'Imagenología → Ecografía'), ('img_ct', 'Imagenología → Tomografía (TC)'), ('img_mri', 'Imagenología → Resonancia (RM)'), ('img_mammography', 'Imagenología → Mamografía'), ('img_densitometry', 'Imagenología → Densitometría'), ('img_fluoroscopy', 'Imagenología → Fluoroscopía'), ('img_angiography', 'Imagenología → Angiografía'), ('img_nuclear', 'Imagenología → Medicina Nuclear'), ('card_ecg', 'Cardiología → Electrocardiograma'), ('card_echo', 'Cardiología → Ecocardiograma'), ('card_stress', 'Cardiología → Prueba de Esfuerzo'), ('card_holter', 'Cardiología → Holter / Monitoreo'), ('neuro_eeg', 'Neurología → Electroencefalograma'), ('neuro_emg', 'Neurología → Electromiografía'), ('neuro_evoked', 'Neurología → Potenciales Evocados'), ('pulmo_spirometry', 'Neumología → Espirometría'), ('pulmo_pft', 'Neumología → Pruebas Funcionales'), ('pulmo_oximetry', 'Neumología → Oximetría'), ('endo_gastro', 'Endoscopía → Gastroscopía'), ('endo_colono', 'Endoscopía → Colonoscopía'), ('endo_broncho', 'Endoscopía → Broncoscopía'), ('ophth_slit', 'Oftalmología → Lámpara de Hendidura'), ('ophth_oct', 'Oftalmología → OCT'), ('ophth_visual', 'Oftalmología → Campo Visual'), ('ophth_tonometry', 'Oftalmología → Tonometría'), ('other_audiometry', 'Otros → Audiometría'), ('other_biopsy', 'Otros → Biopsia'), ('other_genetic', 'Otros → Genética'), ('other_special', 'Otros → Especiales')], default='lab_special', max_length=50),
        ),
        migrations.CreateModel(
            name='BillingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code_prefix', models.CharField(max_length=10, verbose_name='Prefijo de código')),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('sort_order', models.IntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_categories', to='core.institutionsettings')),
            ],
            options={
                'verbose_name': 'Categoría de Facturación',
                'verbose_name_plural': 'Categorías de Facturación',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('institution', 'code_prefix')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalBillingItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Código')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='Moneda')),
                ('estimated_duration', models.IntegerField(blank=True, null=True, verbose_name='Duración estimada (min)')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.billingcategory')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.institutionsettings')),
            ],
            options={
                'verbose_name': 'historical Item de Facturación',
                'verbose_name_plural': 'historical Items de Facturación',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='BillingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Código')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='Moneda')),
                ('estimated_duration', models.IntegerField(blank=True, null=True, verbose_name='Duración estimada (min)')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='core.billingcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_items_created', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_items', to='core.institutionsettings')),
            ],
            options={
                'verbose_name': 'Item de Facturación',
                'verbose_name_plural': 'Items de Facturación',
                'ordering': ['category__sort_order', 'sort_order', 'code'],
                'indexes': [models.Index(fields=['institution', 'is_active'], name='core_billin_institu_1d436a_idx'), models.Index(fields=['institution', 'category'], name='core_billin_institu_36e259_idx')],
                'unique_together': {('institution', 'code')},
            },
        ),
    ]
