# Generated by Django 5.2.7 on 2025-10-27 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_genetic_predispositions_to_historicalpatient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpatient',
            name='genetic_predispositions',
        ),
    ]
