# Generated by Django 5.2.7 on 2025-10-15 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_patient_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula solo puede contener números.', regex='^\\d+$'), django.core.validators.MinLengthValidator(6, message='La cédula debe tener al menos 6 dígitos.'), django.core.validators.MaxLengthValidator(10, message='La cédula no puede tener más de 10 dígitos.')], verbose_name='Cédula de Identidad'),
        ),
    ]
