# Generated by Django 5.2.7 on 2026-05-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_payment_methods_and_crypto_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoroperator',
            name='colegiado_id',
        ),
        migrations.RemoveField(
            model_name='historicaldoctoroperator',
            name='colegiado_id',
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='file_url',
            field=models.CharField(blank=True, help_text='URL pública del archivo en R2 (Cloudflare) o URL absoluta', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='doctoroperator',
            name='license',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Licencia Sanitaria / MPPS'),
        ),
        migrations.AlterField(
            model_name='historicaldoctoroperator',
            name='license',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Licencia Sanitaria / MPPS'),
        ),
    ]
