# Generated by Django 5.2.7 on 2026-02-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_medicaltest_status_alter_medicaltest_test_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chargeorder',
            options={'ordering': ['-issued_at'], 'verbose_name': 'Orden de Cobro', 'verbose_name_plural': 'Órdenes de Cobro'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Altura del paciente en cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso del paciente en kg', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Altura del paciente en cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso del paciente en kg', max_digits=5, null=True),
        ),
    ]
