# Generated by Django 5.2.7 on 2026-02-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_chargeorder_options_appointment_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='profession',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Profesión/Ocupación'),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='skin_type',
            field=models.CharField(blank=True, choices=[('I', 'Tipo I - Muy clara, siempre se quema'), ('II', 'Tipo II - Clara, usualmente se quema'), ('III', 'Tipo III - Intermedia, a veces se quema'), ('IV', 'Tipo IV - Mate, rara vez se quema'), ('V', 'Tipo V - Morena, muy rara vez se quema'), ('VI', 'Tipo VI - Negra, nunca se quema')], max_length=3, null=True, verbose_name='Tipo de piel (Fitzpatrick)'),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='tattoo',
            field=models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No')], null=True, verbose_name='Tiene tatuajes'),
        ),
        migrations.AddField(
            model_name='patient',
            name='profession',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Profesión/Ocupación'),
        ),
        migrations.AddField(
            model_name='patient',
            name='skin_type',
            field=models.CharField(blank=True, choices=[('I', 'Tipo I - Muy clara, siempre se quema'), ('II', 'Tipo II - Clara, usualmente se quema'), ('III', 'Tipo III - Intermedia, a veces se quema'), ('IV', 'Tipo IV - Mate, rara vez se quema'), ('V', 'Tipo V - Morena, muy rara vez se quema'), ('VI', 'Tipo VI - Negra, nunca se quema')], max_length=3, null=True, verbose_name='Tipo de piel (Fitzpatrick)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='tattoo',
            field=models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No')], null=True, verbose_name='Tiene tatuajes'),
        ),
    ]
