# Generated by Django 5.2.7 on 2026-05-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_file_url_to_medical_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mercantilp2cconfig',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='mercantilp2ctransaction',
            name='charge_order',
        ),
        migrations.RemoveField(
            model_name='mercantilp2ctransaction',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='mercantilp2ctransaction',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='doctorpaymentconfig',
            name='mercantil_client_id',
        ),
        migrations.RemoveField(
            model_name='doctorpaymentconfig',
            name='mercantil_enabled',
        ),
        migrations.RemoveField(
            model_name='doctorpaymentconfig',
            name='mercantil_is_test_mode',
        ),
        migrations.RemoveField(
            model_name='doctorpaymentconfig',
            name='mercantil_secret_key',
        ),
        migrations.RemoveField(
            model_name='doctorpaymentconfig',
            name='mercantil_webhook_secret',
        ),
        migrations.AlterField(
            model_name='historicalinstitutionsettings',
            name='active_gateway',
            field=models.CharField(choices=[('none', 'Manual / Registro Interno'), ('banesco_ve', 'Banesco Hub (VE)'), ('stripe', 'Stripe Global'), ('binance_pay', 'Binance Pay'), ('paypal', 'PayPal Business')], default='none', max_length=50, verbose_name='Pasarela de Pagos Activa'),
        ),
        migrations.AlterField(
            model_name='institutionsettings',
            name='active_gateway',
            field=models.CharField(choices=[('none', 'Manual / Registro Interno'), ('banesco_ve', 'Banesco Hub (VE)'), ('stripe', 'Stripe Global'), ('binance_pay', 'Binance Pay'), ('paypal', 'PayPal Business')], default='none', max_length=50, verbose_name='Pasarela de Pagos Activa'),
        ),
        migrations.DeleteModel(
            name='HistoricalMercantilP2CTransaction',
        ),
        migrations.DeleteModel(
            name='MercantilP2CConfig',
        ),
        migrations.DeleteModel(
            name='MercantilP2CTransaction',
        ),
    ]
