# Generated by Django 5.2.7 on 2025-10-27 19:41

from django.db import migrations, models


def forwards(apps, schema_editor):
    WaitingRoomEntry = apps.get_model("core", "WaitingRoomEntry")

    for entry in WaitingRoomEntry.objects.all():
        # Migrar valores antiguos a la nueva estructura
        if entry.priority == "scheduled":
            entry.priority = "normal"
            entry.source_type = "scheduled"
        elif entry.priority == "walkin":
            entry.priority = "normal"
            entry.source_type = "walkin"
        elif entry.priority == "emergency":
            entry.priority = "emergency"
            entry.source_type = "scheduled"
        entry.save(update_fields=["priority", "source_type"])


def backwards(apps, schema_editor):
    WaitingRoomEntry = apps.get_model("core", "WaitingRoomEntry")

    for entry in WaitingRoomEntry.objects.all():
        # Revertir a los valores antiguos
        if entry.priority == "normal" and entry.source_type == "scheduled":
            entry.priority = "scheduled"
        elif entry.priority == "normal" and entry.source_type == "walkin":
            entry.priority = "walkin"
        elif entry.priority == "emergency":
            entry.priority = "emergency"
        entry.save(update_fields=["priority"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_historicalpatient_genetic_predispositions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitingroomentry',
            options={
                'ordering': [
                    models.Case(
                        models.When(priority='emergency', then=0),
                        default=1,
                        output_field=models.IntegerField(),
                    ),
                    'arrival_time',
                    'order',
                ],
                'verbose_name': 'Waiting Room Entry',
                'verbose_name_plural': 'Waiting Room Entries',
            },
        ),
        migrations.AddField(
            model_name='waitingroomentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='waitingroomentry',
            name='source_type',
            field=models.CharField(
                choices=[('scheduled', 'Scheduled'), ('walkin', 'Walk-in')],
                default='scheduled',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='waitingroomentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='waitingroomentry',
            name='priority',
            field=models.CharField(
                choices=[('normal', 'Normal'), ('emergency', 'Emergency')],
                default='normal',
                max_length=20,
            ),
        ),
        migrations.RunPython(forwards, backwards),
    ]
