# Generated by Django 5.2.7 on 2025-10-15 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_patient_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco emisor (si aplica)'),
        ),
        migrations.AddField(
            model_name='payment',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro'),
        ),
        migrations.AddField(
            model_name='payment',
            name='received_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Recibido por'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de referencia / comprobante'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='core.appointment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta'), ('transfer', 'Transferencia')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('canceled', 'Cancelado'), ('waived', 'Exonerado')], default='pending', max_length=20),
        ),
    ]
