# Generated by Django 5.2.7 on 2026-05-28 18:58

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_mercantilp2cconfig_institution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BancaribeAPIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, help_text='Client ID de la aplicación Bancaribe', max_length=100, verbose_name='Client ID')),
                ('client_secret', models.CharField(blank=True, help_text='Client Secret de la aplicación Bancaribe', max_length=255, verbose_name='Client Secret')),
                ('webhook_secret', models.CharField(blank=True, help_text='Secret para verificar webhooks de Bancaribe', max_length=100, verbose_name='Webhook Secret')),
                ('is_test_mode', models.BooleanField(default=True, help_text='Usar ambiente de pruebas de Bancaribe', verbose_name='Modo Sandbox')),
                ('is_active', models.BooleanField(default=False, help_text='Habilitar integración con Bancaribe', verbose_name='Activo')),
                ('settlement_account', models.CharField(blank=True, help_text='Cuenta bancaria de MEDOPZ para recibir fondos', max_length=50, verbose_name='Cuenta de Liquidación')),
                ('settlement_bank_code', models.CharField(blank=True, help_text='Código del banco de liquidación (ej: 0114 Bancaribe)', max_length=4, verbose_name='Código Banco Liquidación')),
                ('auto_verify_payments', models.BooleanField(default=True, help_text='Verificar pagos automáticamente via API', verbose_name='Verificación Automática')),
                ('auto_disbursement_enabled', models.BooleanField(default=False, help_text='Desembolsar a doctores automáticamente', verbose_name='Desembolso Automático')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bancaribe_config', to='core.institutionsettings', verbose_name='Institución')),
            ],
            options={
                'verbose_name': 'Configuración Bancaribe',
                'verbose_name_plural': 'Configuraciones Bancaribe',
                'db_table': 'bancaribe_api_config',
            },
        ),
        migrations.CreateModel(
            name='DoctorWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Balance Disponible')),
                ('pending_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto en proceso de desembolso', max_digits=12, verbose_name='Balance Pendiente')),
                ('total_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Ganado')),
                ('total_disbursed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Desembolsado')),
                ('last_disbursement_at', models.DateTimeField(blank=True, null=True, verbose_name='Último Desembolso')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='core.doctoroperator', verbose_name='Doctor')),
            ],
            options={
                'verbose_name': 'Wallet Doctor',
                'verbose_name_plural': 'Wallets Doctores',
                'db_table': 'doctor_wallet',
            },
        ),
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Referencia única del desembolso', max_length=50, unique=True, verbose_name='Referencia')),
                ('bancaribe_reference', models.CharField(blank=True, help_text='Referencia retornada por Bancaribe', max_length=100, verbose_name='Referencia Bancaribe')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Moneda')),
                ('amount_ves', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto VES')),
                ('bank_code', models.CharField(max_length=4, verbose_name='Código Banco')),
                ('bank_account', models.CharField(max_length=50, verbose_name='Cuenta Bancaria')),
                ('bank_reference', models.CharField(blank=True, max_length=50, verbose_name='Referencia Bancaria')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado')),
                ('disbursement_type', models.CharField(choices=[('instant', 'Instantáneo'), ('scheduled', 'Programado'), ('batch', 'Lote')], default='scheduled', max_length=20, verbose_name='Tipo')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Programado Para')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Procesado En')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado En')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje Error')),
                ('raw_response', models.JSONField(blank=True, null=True, verbose_name='Respuesta Raw')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='core.doctoroperator', verbose_name='Doctor')),
                ('doctor_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursements', to='core.doctorwallet', verbose_name='Wallet Origen')),
            ],
            options={
                'verbose_name': 'Desembolso',
                'verbose_name_plural': 'Desembolsos',
                'db_table': 'disbursement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Bruto')),
                ('commission_rate', models.DecimalField(decimal_places=4, help_text='Porcentaje de comisión (ej: 0.03 = 3%)', max_digits=5, verbose_name='Tasa Comisión')),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Comisión')),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Monto que recibe el doctor', max_digits=12, verbose_name='Monto Neto')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Moneda')),
                ('exchange_rate_bcv', models.DecimalField(blank=True, decimal_places=2, help_text='Tasa de cambio USD/VES al momento', max_digits=12, null=True, verbose_name='Tasa BCV')),
                ('amount_ves', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto VES')),
                ('is_settled', models.BooleanField(default=False, help_text='Si la comisión ha sido liquidada a MEDOPZ', verbose_name='Liquidado')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Liquidación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='core.paymenttransaction', verbose_name='Transacción')),
            ],
            options={
                'verbose_name': 'Ganancia Plataforma',
                'verbose_name_plural': 'Ganancias Plataforma',
                'db_table': 'platform_earnings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VueltoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Referencia')),
                ('bancaribe_reference', models.CharField(blank=True, max_length=100, verbose_name='Referencia Bancaribe')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('currency', models.CharField(default='VES', max_length=3, verbose_name='Moneda')),
                ('patient_phone', models.CharField(max_length=20, verbose_name='Teléfono Paciente')),
                ('patient_national_id', models.CharField(max_length=20, verbose_name='Cédula Paciente')),
                ('patient_bank_code', models.CharField(max_length=4, verbose_name='Código Banco')),
                ('otp_code', models.CharField(blank=True, help_text='Código OTP enviado al paciente para confirmar', max_length=6, verbose_name='Código OTP')),
                ('otp_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='OTP Enviado En')),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='OTP Expira En')),
                ('otp_verified', models.BooleanField(default=False, verbose_name='OTP Verificado')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('delivered', 'Entregado'), ('failed', 'Fallido'), ('expired', 'Expirado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje Error')),
                ('raw_response', models.JSONField(blank=True, null=True, verbose_name='Respuesta Raw')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuelto_requests', to='core.paymenttransaction', verbose_name='Transacción Original')),
            ],
            options={
                'verbose_name': 'Solicitud Vuelto',
                'verbose_name_plural': 'Solicitudes Vuelto',
                'db_table': 'vuelto_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
