# Generated by Django 5.2.7 on 2026-02-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_historicalpatient_profession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='description',
        ),
        migrations.AddField(
            model_name='familyhistory',
            name='age_at_diagnosis',
            field=models.PositiveIntegerField(blank=True, help_text='Edad del familiar al momento del diagnóstico', null=True),
        ),
        migrations.AddField(
            model_name='familyhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='activity_description',
            field=models.TextField(blank=True, help_text='Tipo de actividad: caminar, gimnasio, deportes, etc.', null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='alcohol_frequency',
            field=models.CharField(blank=True, choices=[('never', 'Nunca'), ('monthly_or_less', 'Mensual o menos'), ('2_4_month', '2-4 veces al mes'), ('2_3_week', '2-3 veces por semana'), ('4_plus_week', '4+ veces por semana')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='alcohol_quantity',
            field=models.CharField(blank=True, choices=[('1_2', '1-2'), ('3_4', '3-4'), ('5_6', '5-6'), ('7_9', '7-9'), ('10_plus', '10+')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='binge_frequency',
            field=models.CharField(blank=True, choices=[('never', 'Nunca'), ('less_monthly', 'Menos que mensual'), ('monthly', 'Mensual'), ('weekly', 'Semanal'), ('daily', 'Diario o casi diario')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='cigarettes_per_day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='diet_restrictions',
            field=models.TextField(blank=True, help_text='Restricciones especiales: renal, diabética, etc.', null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='diet_type',
            field=models.CharField(blank=True, choices=[('omnivore', 'Omnívora'), ('vegetarian', 'Vegetariana'), ('vegan', 'Vegana'), ('mediterranean', 'Mediterránea'), ('other', 'Otra')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='drinks_alcohol',
            field=models.CharField(blank=True, choices=[('yes', 'Sí consume'), ('no', 'No consume')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='drug_description',
            field=models.TextField(blank=True, help_text='Tipo de drogas consumidas', null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='drug_frequency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='exercise_frequency',
            field=models.CharField(blank=True, choices=[('sedentary', 'Sedentario'), ('1_2_week', '1-2 veces por semana'), ('3_4_week', '3-4 veces por semana'), ('5_plus_week', '5+ veces por semana')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='exercise_intensity',
            field=models.CharField(blank=True, choices=[('light', 'Leve'), ('moderate', 'Moderada'), ('intense', 'Intensa')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='sleep_hours',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Horas de sueño por noche', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='sleep_quality',
            field=models.CharField(blank=True, choices=[('good', 'Buena'), ('fair', 'Regular'), ('poor', 'Mala')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='smokes_currently',
            field=models.CharField(blank=True, choices=[('yes', 'Sí, fuma actualmente'), ('no', 'No fuma'), ('former', 'Ex fumador')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='smoking_frequency',
            field=models.CharField(blank=True, choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('occasional', 'Ocasional')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='smoking_start_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='tobacco_type',
            field=models.CharField(blank=True, choices=[('cigarettes', 'Cigarrillos'), ('pipe', 'Pipa'), ('electronic', 'Cigarrillo electrónico'), ('other', 'Otros')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='uses_drugs',
            field=models.CharField(blank=True, choices=[('yes', 'Sí'), ('no', 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='relative',
            field=models.CharField(choices=[('mother', 'Madre'), ('father', 'Padre'), ('sibling', 'Hermano/a'), ('child', 'Hijo/a'), ('maternal_grandmother', 'Abuela materna'), ('maternal_grandfather', 'Abuelo materno'), ('paternal_grandmother', 'Abuela paterna'), ('paternal_grandfather', 'Abuelo paterno'), ('uncle', 'Tío/a'), ('aunt', 'Tía'), ('cousin', 'Primo/a'), ('nephew', 'Sobrino/a'), ('niece', 'Sobrina/a')], max_length=100),
        ),
        migrations.AlterField(
            model_name='habit',
            name='type',
            field=models.CharField(choices=[('tabaco', 'Tabaco'), ('alcohol', 'Alcohol'), ('actividad_fisica', 'Actividad física'), ('dieta', 'Dieta'), ('sueno', 'Sueño'), ('drogas', 'Drogas')], max_length=50),
        ),
    ]
