# Generated by Django 5.2.7 on 2026-03-01 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_habit_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='consent_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de consentimiento parental'),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='is_minor',
            field=models.BooleanField(default=False, help_text='Determina si el paciente es menor de 18 años', verbose_name='¿Es menor de edad?'),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='parental_consent',
            field=models.BooleanField(default=False, help_text='Confirmación de consentimiento para tratamiento de menor', verbose_name='Consentimiento parental firmado'),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='relationship_type',
            field=models.CharField(blank=True, choices=[('father', 'Padre'), ('mother', 'Madre'), ('legal_guardian', 'Tutor Legal'), ('grandfather', 'Abuelo'), ('grandmother', 'Abuela'), ('sibling', 'Hermano/Hermana'), ('other', 'Otro')], max_length=20, null=True, verbose_name='Tipo de relación con el representante'),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='representative',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.patient', verbose_name='Representante (padre/madre/tutor)'),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='representative_doc',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Cédula del representante'),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='representative_email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email del representante'),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='representative_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del representante'),
        ),
        migrations.AddField(
            model_name='patient',
            name='consent_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de consentimiento parental'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_minor',
            field=models.BooleanField(default=False, help_text='Determina si el paciente es menor de 18 años', verbose_name='¿Es menor de edad?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='parental_consent',
            field=models.BooleanField(default=False, help_text='Confirmación de consentimiento para tratamiento de menor', verbose_name='Consentimiento parental firmado'),
        ),
        migrations.AddField(
            model_name='patient',
            name='relationship_type',
            field=models.CharField(blank=True, choices=[('father', 'Padre'), ('mother', 'Madre'), ('legal_guardian', 'Tutor Legal'), ('grandfather', 'Abuelo'), ('grandmother', 'Abuela'), ('sibling', 'Hermano/Hermana'), ('other', 'Otro')], max_length=20, null=True, verbose_name='Tipo de relación con el representante'),
        ),
        migrations.AddField(
            model_name='patient',
            name='representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_patients', to='core.patient', verbose_name='Representante (padre/madre/tutor)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='representative_doc',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Cédula del representante'),
        ),
        migrations.AddField(
            model_name='patient',
            name='representative_email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email del representante'),
        ),
        migrations.AddField(
            model_name='patient',
            name='representative_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del representante'),
        ),
    ]
