# Generated by Django 5.2.7 on 2026-05-28 20:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_bancaribe_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorpaymentconfig',
            name='min_disbursement_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Monto mínimo para solicitar desembolso (default $20 USD)', max_digits=10, verbose_name='Monto Mínimo Disbursement'),
        ),
    ]
