# Generated by Django 5.2.7 on 2025-11-03

from django.db import migrations, transaction
from decimal import Decimal


def migrate_payments_to_orders(apps, schema_editor):
    Appointment = apps.get_model("core", "Appointment")
    ChargeOrder = apps.get_model("core", "ChargeOrder")
    ChargeItem = apps.get_model("core", "ChargeItem")
    Payment = apps.get_model("core", "Payment")

    with transaction.atomic():
        for appt in Appointment.objects.all():
            # Solo citas con monto esperado > 0
            if appt.expected_amount and appt.expected_amount > Decimal("0.00"):
                order, created = ChargeOrder.objects.get_or_create(
                    appointment_id=appt.id,
                    patient_id=appt.patient_id,
                    defaults={
                        "currency": "USD",
                        "status": "open",
                        "issued_by": "migration",
                    },
                )
                if created:
                    # Crear ítem base con subtotal calculado manualmente
                    ChargeItem.objects.create(
                        order=order,
                        code="CONSULTA",
                        description=f"Consulta {appt.appointment_type}",
                        qty=Decimal("1.00"),
                        unit_price=appt.expected_amount,
                        subtotal=(Decimal("1.00") * appt.expected_amount),  # 👈 FIX
                    )
                    order.recalc_totals()
                    order.save(update_fields=["total", "balance_due"])

                # Reasignar pagos existentes
                for pay in Payment.objects.filter(
                    appointment_id=appt.id, charge_order__isnull=True
                ):
                    pay.charge_order_id = order.id
                    # Normalizar estados antiguos
                    if pay.status == "paid":
                        pay.status = "confirmed"
                    pay.save(update_fields=["charge_order", "status"])
                    order.recalc_totals()
                    order.save(update_fields=["balance_due"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_historicalchargeorder_historicalpayment_currency_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_payments_to_orders, migrations.RunPython.noop),
    ]
