# Generated by Django 5.2.7 on 2025-10-19 14:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_payment_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='expected_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Monto esperado'),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='expected_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Monto esperado'),
        ),
    ]
