# Generated by Django 5.2.7 on 2026-03-02 00:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_historicalpatient_consent_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email de acceso')),
                ('password_hash', models.CharField(max_length=255, verbose_name='Hash de contraseña')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Email verificado')),
                ('verification_token', models.CharField(blank=True, max_length=255, null=True)),
                ('verification_token_expires', models.DateTimeField(blank=True, null=True)),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='2FA habilitado')),
                ('two_factor_secret', models.CharField(blank=True, max_length=32, null=True)),
                ('two_factor_backup_codes', models.JSONField(default=list, verbose_name='Códigos de respaldo')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='Teléfono verificado')),
                ('id_document_type', models.CharField(blank=True, choices=[('cedula', 'Cédula'), ('pasaporte', 'Pasaporte'), ('extranjero', 'Cédula Extranjería')], max_length=20, null=True, verbose_name='Tipo de documento')),
                ('id_document_front', models.ImageField(blank=True, null=True, upload_to='patient_id/', verbose_name='Documento frontal')),
                ('id_document_back', models.ImageField(blank=True, null=True, upload_to='patient_id/', verbose_name='Documento reverso')),
                ('id_verified', models.BooleanField(default=False, verbose_name='Identidad verificada')),
                ('id_verified_at', models.DateTimeField(blank=True, null=True)),
                ('notifications_email', models.BooleanField(default=True, verbose_name='Notificaciones por email')),
                ('notifications_sms', models.BooleanField(default=True, verbose_name='Notificaciones por SMS')),
                ('notifications_whatsapp', models.BooleanField(default=True, verbose_name='Notificaciones por WhatsApp')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='Último login')),
                ('failed_login_attempts', models.IntegerField(default=0, verbose_name='Intentos fallidos')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='Bloqueado hasta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_user', to='core.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Usuario Paciente',
                'verbose_name_plural': 'Usuarios Pacientes',
                'db_table': 'patient_users',
            },
        ),
        migrations.CreateModel(
            name='PatientSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free - Básico'), ('basic', 'Básico'), ('premium', 'Premium'), ('enterprise', 'Empresarial')], default='free', max_length=20, verbose_name='Plan')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('pending', 'Pendiente'), ('suspended', 'Suspendida'), ('cancelled', 'Cancelada'), ('expired', 'Expirada')], default='pending', max_length=20, verbose_name='Estado')),
                ('monthly_price_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Precio mensual USD')),
                ('monthly_price_ves', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Precio mensual VES')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('billing_cycle_day', models.IntegerField(default=1, verbose_name='Día de facturación (1-28)')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='Renovación automática')),
                ('cancel_at_period_end', models.BooleanField(default=False, verbose_name='Cancelar al fin de período')),
                ('payment_method', models.CharField(blank=True, max_length=30, null=True, verbose_name='Método de pago')),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia de pago')),
                ('features', models.JSONField(default=dict, verbose_name='Características incluidas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.patient', verbose_name='Paciente')),
                ('patient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.patientuser', verbose_name='Usuario paciente')),
            ],
            options={
                'verbose_name': 'Suscripción Paciente',
                'verbose_name_plural': 'Suscripciones Pacientes',
                'db_table': 'patient_subscriptions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PatientSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=255, unique=True, verbose_name='Token de acceso')),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Token de refresh')),
                ('ip_address', models.GenericIPAddressField(null=True, verbose_name='IP')),
                ('user_agent', models.TextField(null=True, verbose_name='User Agent')),
                ('device_info', models.JSONField(default=dict, verbose_name='Información del dispositivo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('expires_at', models.DateTimeField(verbose_name='Expira')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True, verbose_name='Última actividad')),
                ('patient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.patientuser', verbose_name='Usuario paciente')),
            ],
            options={
                'verbose_name': 'Sesión Paciente',
                'verbose_name_plural': 'Sesiones Pacientes',
                'db_table': 'patient_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('failed_login', 'Login fallido'), ('password_change', 'Cambio de contraseña'), ('profile_update', 'Actualización de perfil'), ('view_history', 'Ver historia clínica'), ('book_appointment', 'Reservar cita'), ('cancel_appointment', 'Cancelar cita'), ('view_payment', 'Ver pago'), ('make_payment', 'Realizar pago'), ('2fa_enable', 'Habilitar 2FA'), ('2fa_disable', 'Deshabilitar 2FA')], max_length=30, verbose_name='Acción')),
                ('ip_address', models.GenericIPAddressField(null=True, verbose_name='IP')),
                ('user_agent', models.TextField(null=True, verbose_name='User Agent')),
                ('device_info', models.JSONField(default=dict, verbose_name='Información del dispositivo')),
                ('metadata', models.JSONField(default=dict, verbose_name='Metadatos adicionales')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='core.patient', verbose_name='Paciente')),
                ('patient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='core.patientuser', verbose_name='Usuario paciente')),
            ],
            options={
                'verbose_name': 'Log de Acceso Paciente',
                'verbose_name_plural': 'Logs de Acceso Pacientes',
                'db_table': 'patient_access_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='patientuser',
            index=models.Index(fields=['email'], name='patient_use_email_8ef8ae_idx'),
        ),
        migrations.AddIndex(
            model_name='patientuser',
            index=models.Index(fields=['patient'], name='patient_use_patient_e13355_idx'),
        ),
        migrations.AddIndex(
            model_name='patientuser',
            index=models.Index(fields=['is_active'], name='patient_use_is_acti_db7bf4_idx'),
        ),
        migrations.AddIndex(
            model_name='patientsubscription',
            index=models.Index(fields=['patient', 'status'], name='patient_sub_patient_c22cec_idx'),
        ),
        migrations.AddIndex(
            model_name='patientsubscription',
            index=models.Index(fields=['status', 'end_date'], name='patient_sub_status_41cc26_idx'),
        ),
        migrations.AddIndex(
            model_name='patientsession',
            index=models.Index(fields=['patient_user', 'is_active'], name='patient_ses_patient_94ece3_idx'),
        ),
        migrations.AddIndex(
            model_name='patientsession',
            index=models.Index(fields=['access_token'], name='patient_ses_access__4bfb33_idx'),
        ),
        migrations.AddIndex(
            model_name='patientaccesslog',
            index=models.Index(fields=['patient_user', '-created_at'], name='patient_acc_patient_95fc48_idx'),
        ),
        migrations.AddIndex(
            model_name='patientaccesslog',
            index=models.Index(fields=['action', '-created_at'], name='patient_acc_action_d47616_idx'),
        ),
    ]
