# Generated by Django 5.2.7 on 2026-06-02 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_min_disbursement_amount'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chargeitem',
            index=models.Index(fields=['order', 'code'], name='core_charge_order_i_3090e6_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitalization',
            index=models.Index(fields=['patient', 'admission_date'], name='core_hospit_patient_8cddb4_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitalization',
            index=models.Index(fields=['institution', 'status'], name='core_hospit_institu_d89db0_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitalization',
            index=models.Index(fields=['attending_doctor', 'status'], name='core_hospit_attendi_43f34f_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['doctor', 'issued_at'], name='core_prescr_doctor__3d44d2_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['institution', 'issued_at'], name='core_prescr_institu_a2e8d1_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', 'issued_at'], name='core_prescr_patient_b456f9_idx'),
        ),
        migrations.AddIndex(
            model_name='surgery',
            index=models.Index(fields=['patient', 'scheduled_date'], name='core_surger_patient_cbb456_idx'),
        ),
        migrations.AddIndex(
            model_name='surgery',
            index=models.Index(fields=['institution', 'status'], name='core_surger_institu_fa69df_idx'),
        ),
        migrations.AddIndex(
            model_name='surgery',
            index=models.Index(fields=['surgeon', 'status'], name='core_surger_surgeon_86aca1_idx'),
        ),
    ]
