# Generated by Django 5.2.7 on 2025-11-03 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_migrate_payments_to_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='charge_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.chargeorder'),
        ),
    ]
