# Generated by Django 5.2.7 on 2026-06-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinstitutionsettings',
            name='logo_url',
            field=models.CharField(blank=True, help_text='URL pública del logo en R2 (Cloudflare) o URL absoluta', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='institutionsettings',
            name='logo_url',
            field=models.CharField(blank=True, help_text='URL pública del logo en R2 (Cloudflare) o URL absoluta', max_length=500, null=True),
        ),
    ]
