# Generated by Django 5.2.7 on 2026-03-02 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_patientuser_patientsubscription_patientsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoroperator',
            name='reminder_hours_before',
            field=models.IntegerField(default=24, verbose_name='Horas antes para recordatorio'),
        ),
        migrations.AddField(
            model_name='doctoroperator',
            name='whatsapp_access_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='WhatsApp Access Token'),
        ),
        migrations.AddField(
            model_name='doctoroperator',
            name='whatsapp_business_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='WhatsApp Business ID'),
        ),
        migrations.AddField(
            model_name='doctoroperator',
            name='whatsapp_business_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número WhatsApp Business'),
        ),
        migrations.AddField(
            model_name='doctoroperator',
            name='whatsapp_enabled',
            field=models.BooleanField(default=False, verbose_name='WhatsApp habilitado'),
        ),
        migrations.AddField(
            model_name='doctoroperator',
            name='whatsapp_webhook_verify_token',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Webhook Verify Token'),
        ),
        migrations.AddField(
            model_name='historicaldoctoroperator',
            name='reminder_hours_before',
            field=models.IntegerField(default=24, verbose_name='Horas antes para recordatorio'),
        ),
        migrations.AddField(
            model_name='historicaldoctoroperator',
            name='whatsapp_access_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='WhatsApp Access Token'),
        ),
        migrations.AddField(
            model_name='historicaldoctoroperator',
            name='whatsapp_business_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='WhatsApp Business ID'),
        ),
        migrations.AddField(
            model_name='historicaldoctoroperator',
            name='whatsapp_business_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número WhatsApp Business'),
        ),
        migrations.AddField(
            model_name='historicaldoctoroperator',
            name='whatsapp_enabled',
            field=models.BooleanField(default=False, verbose_name='WhatsApp habilitado'),
        ),
        migrations.AddField(
            model_name='historicaldoctoroperator',
            name='whatsapp_webhook_verify_token',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Webhook Verify Token'),
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('reminder', 'Recordatorio'), ('confirmation', 'Confirmación'), ('cancellation', 'Cancelación'), ('notification', 'Notificación'), ('chat', 'Chat')], default='notification', max_length=20, verbose_name='Tipo de mensaje')),
                ('content', models.TextField(verbose_name='Contenido del mensaje')),
                ('phone_to', models.CharField(max_length=20, verbose_name='Teléfono destinatario')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('delivered', 'Entregado'), ('read', 'Leído'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado a las')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregado a las')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Leído a las')),
                ('whatsapp_message_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de mensaje WhatsApp')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensaje de error')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='core.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='core.doctoroperator')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='core.patient')),
            ],
            options={
                'verbose_name': 'Mensaje WhatsApp',
                'verbose_name_plural': 'Mensajes WhatsApp',
                'db_table': 'whatsapp_messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', '-created_at'], name='whatsapp_me_patient_4f2829_idx'), models.Index(fields=['doctor', '-created_at'], name='whatsapp_me_doctor__10af1a_idx'), models.Index(fields=['status'], name='whatsapp_me_status_63922d_idx')],
            },
        ),
    ]
