# Generated by Django 5.2.7 on 2025-10-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_init_expected_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('general', 'Consulta General'), ('specialized', 'Consulta Especializada')], default='general', max_length=20, verbose_name='Tipo de consulta'),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='appointment_type',
            field=models.CharField(choices=[('general', 'Consulta General'), ('specialized', 'Consulta Especializada')], default='general', max_length=20, verbose_name='Tipo de consulta'),
        ),
    ]
