# Generated by Django 5.2.7 on 2026-06-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_logo_url_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoroperator',
            name='signature_url',
            field=models.URLField(blank=True, help_text='URL permanente de la firma digitalizada en Cloudflare R2', max_length=500, null=True, verbose_name='URL de firma en R2'),
        ),
        migrations.AddField(
            model_name='historicaldoctoroperator',
            name='signature_url',
            field=models.URLField(blank=True, help_text='URL permanente de la firma digitalizada en Cloudflare R2', max_length=500, null=True, verbose_name='URL de firma en R2'),
        ),
    ]
