# Generated by Django 5.2.7 on 2026-03-02 18:27

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_doctoroperator_reminder_hours_before_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código único: mercantil, banesco, binance, manual', max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('name_en', models.CharField(max_length=100, verbose_name='Nombre (English)')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('requires_legal_account', models.BooleanField(default=False, help_text='Si True, el doctor debe tener cuenta jurídica para usar este método', verbose_name='Requiere cuenta jurídica')),
                ('logo_url', models.URLField(blank=True, max_length=500, verbose_name='URL del Logo')),
                ('api_docs_url', models.URLField(blank=True, max_length=500, verbose_name='URL de Documentación API')),
                ('config_schema', models.JSONField(default=dict, help_text='JSON que define los campos de configuración requeridos', verbose_name='Esquema de configuración')),
                ('supports_webhook', models.BooleanField(default=False, verbose_name='Soporta Webhook')),
                ('supports_api_verify', models.BooleanField(default=False, verbose_name='Soporta verificación por API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pasarela de Pago',
                'verbose_name_plural': 'Pasarelas de Pago',
                'db_table': 'payment_gateways',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorPaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre del Banco')),
                ('bank_account', models.CharField(blank=True, max_length=50, verbose_name='Número de Cuenta')),
                ('bank_rif', models.CharField(blank=True, max_length=20, verbose_name='RIF / Cédula')),
                ('bank_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono asociado al Pago Móvil')),
                ('bank_account_holder', models.CharField(blank=True, max_length=200, verbose_name='Titular de la Cuenta')),
                ('mercantil_client_id', models.CharField(blank=True, max_length=100, verbose_name='Mercantil - Client ID')),
                ('mercantil_secret_key', models.CharField(blank=True, max_length=255, verbose_name='Mercantil - Secret Key')),
                ('mercantil_webhook_secret', models.CharField(blank=True, max_length=100, verbose_name='Mercantil - Webhook Secret')),
                ('mercantil_enabled', models.BooleanField(default=False, verbose_name='Mercantil habilitado')),
                ('mercantil_is_test_mode', models.BooleanField(default=True, verbose_name='Mercantil modo prueba')),
                ('banesco_client_id', models.CharField(blank=True, max_length=100, verbose_name='Banesco - Client ID')),
                ('banesco_secret_key', models.CharField(blank=True, max_length=255, verbose_name='Banesco - Secret Key')),
                ('banesco_enabled', models.BooleanField(default=False, verbose_name='Banesco habilitado')),
                ('banesco_is_test_mode', models.BooleanField(default=True, verbose_name='Banesco modo prueba')),
                ('binance_merchant_id', models.CharField(blank=True, max_length=100, verbose_name='Binance - Merchant ID')),
                ('binance_api_key', models.CharField(blank=True, max_length=255, verbose_name='Binance - API Key')),
                ('binance_api_secret', models.CharField(blank=True, max_length=255, verbose_name='Binance - API Secret')),
                ('binance_webhook_secret', models.CharField(blank=True, max_length=100, verbose_name='Binance - Webhook Secret')),
                ('binance_enabled', models.BooleanField(default=False, verbose_name='Binance habilitado')),
                ('account_type', models.CharField(choices=[('natural', 'Persona Natural'), ('juridica', 'Persona Jurídica')], default='natural', max_length=20, verbose_name='Tipo de Cuenta')),
                ('manual_verification_enabled', models.BooleanField(default=True, help_text='Permitir que pacientes confirmen pagos manualmente como fallback', verbose_name='Verificación manual habilitada')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Notificaciones habilitadas')),
                ('commission_doctor_percent', models.DecimalField(decimal_places=2, default=Decimal('3.0'), help_text='Porcentaje que paga el doctor por transacción', max_digits=5, verbose_name='% Comisión Doctor')),
                ('commission_patient_percent', models.DecimalField(decimal_places=2, default=Decimal('2.0'), help_text='Porcentaje que paga el paciente por transacción', max_digits=5, verbose_name='% Comisión Paciente')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Configuración verificada')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de verificación')),
                ('verification_notes', models.TextField(blank=True, verbose_name='Notas de verificación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_config', to='core.doctoroperator', verbose_name='Doctor')),
                ('enabled_methods', models.ManyToManyField(blank=True, related_name='doctor_configs', to='core.paymentgateway', verbose_name='Métodos de pago habilitados')),
            ],
            options={
                'verbose_name': 'Configuración de Pago Doctor',
                'verbose_name_plural': 'Configuraciones de Pago Doctor',
                'db_table': 'doctor_payment_config',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Referencia única para tracking', unique=True, verbose_name='UUID único')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('currency', models.CharField(choices=[('VES', 'Bolívar - VES'), ('USD', 'Dólar - USD')], default='VES', max_length=3, verbose_name='Moneda')),
                ('amount_ves', models.DecimalField(blank=True, decimal_places=2, help_text='Monto convertido a VES (si pagó en USD)', max_digits=12, null=True, verbose_name='Monto en VES')),
                ('exchange_rate_bcv', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tasa BCV usada')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Descripción del pago')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('confirmed', 'Confirmado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado')),
                ('verification_type', models.CharField(choices=[('api', 'Automática (API)'), ('manual', 'Manual (Doctor)'), ('webhook', 'Webhook')], default='manual', max_length=20, verbose_name='Tipo de verificación')),
                ('payer_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre del pagador')),
                ('payer_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono del pagador')),
                ('payer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email del pagador')),
                ('reference_number', models.CharField(blank=True, help_text='Referencia que el paciente reporta haber realizado', max_length=100, verbose_name='Número de referencia (del paciente)')),
                ('gateway_transaction_id', models.CharField(blank=True, help_text='ID retornado por el banco/pasarela', max_length=255, verbose_name='ID de transacción del gateway')),
                ('bank_reference', models.CharField(blank=True, help_text='Referencia oficial del banco', max_length=100, verbose_name='Referencia bancaria')),
                ('commission_doctor_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto comisión doctor')),
                ('commission_patient_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto comisión paciente')),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto neto al doctor')),
                ('gateway_response', models.JSONField(blank=True, help_text='Respuesta completa de API del banco/pasarela', null=True, verbose_name='Respuesta del Gateway')),
                ('notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Notas privadas del doctor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha en que paciente reporta haber pagado')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de confirmación real')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de expiración')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='core.doctoroperator', verbose_name='Doctor')),
                ('linked_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateway_transactions', to='core.payment', verbose_name='Pago vinculado (cita)')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='core.patient', verbose_name='Paciente')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.paymentgateway', verbose_name='Método de Pago')),
            ],
            options={
                'verbose_name': 'Transacción de Pago',
                'verbose_name_plural': 'Transacciones de Pago',
                'db_table': 'payment_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(help_text='Tipo de evento recibido (ej: PAY_CLOSED, PAYMENT_CONFIRMED)', max_length=100, verbose_name='Tipo de evento')),
                ('payload', models.JSONField(help_text='Cuerpo completo del webhook', verbose_name='Payload recibido')),
                ('headers', models.JSONField(blank=True, null=True, verbose_name='Headers recibidos')),
                ('signature_valid', models.BooleanField(default=False, verbose_name='Firma válida')),
                ('signature_error', models.TextField(blank=True, verbose_name='Error de firma')),
                ('status', models.CharField(choices=[('received', 'Recibido'), ('processing', 'Procesando'), ('processed', 'Procesado'), ('failed', 'Fallido'), ('duplicate', 'Duplicado')], default='received', max_length=20, verbose_name='Estado')),
                ('processing_error', models.TextField(blank=True, verbose_name='Error de procesamiento')),
                ('response_sent', models.JSONField(blank=True, null=True, verbose_name='Respuesta enviada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de procesamiento')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_webhooks', to='core.doctoroperator', verbose_name='Doctor')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webhooks', to='core.paymentgateway', verbose_name='Gateway')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhooks', to='core.paymenttransaction', verbose_name='Transacción vinculada')),
            ],
            options={
                'verbose_name': 'Webhook de Pago',
                'verbose_name_plural': 'Webhooks de Pago',
                'db_table': 'payment_webhooks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['doctor', 'status'], name='payment_tra_doctor__fe0d5a_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['doctor', '-created_at'], name='payment_tra_doctor__2779c0_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['patient', 'status'], name='payment_tra_patient_8870f6_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['uuid'], name='payment_tra_uuid_7fbd8f_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['gateway_transaction_id'], name='payment_tra_gateway_532615_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['reference_number'], name='payment_tra_referen_0f91ab_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status', 'created_at'], name='payment_tra_status_ea288f_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhook',
            index=models.Index(fields=['doctor', '-created_at'], name='payment_web_doctor__472748_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhook',
            index=models.Index(fields=['gateway', 'status'], name='payment_web_gateway_724434_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhook',
            index=models.Index(fields=['transaction'], name='payment_web_transac_9fe51d_idx'),
        ),
    ]
