# Generated by Django 5.2.7 on 2026-03-03 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_paymentgateway_doctorpaymentconfig_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Django'),
        ),
        migrations.AlterField(
            model_name='patientuser',
            name='password_hash',
            field=models.CharField(blank=True, max_length=255, verbose_name='Hash de contraseña (legacy)'),
        ),
        migrations.AddIndex(
            model_name='patientuser',
            index=models.Index(fields=['user'], name='patient_use_user_id_64a1ac_idx'),
        ),
    ]
