# Generated by Django 5.2.7 on 2025-10-20 13:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_appointment_appointment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingRoomEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('in_consultation', 'In Consultation'), ('completed', 'Completed')], default='waiting', max_length=20)),
                ('priority', models.CharField(choices=[('scheduled', 'Scheduled'), ('walkin', 'Walk-in'), ('emergency', 'Emergency')], default='scheduled', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
            options={
                'ordering': ['order', 'arrival_time'],
            },
        ),
    ]
