# Generated by Django 5.2.7 on 2025-11-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_chargeorder_created_at_chargeorder_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='severity',
            field=models.CharField(blank=True, help_text='info | warning | critical', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='chargeorder',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('void', 'Void'), ('waived', 'Waived')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalchargeorder',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('void', 'Void'), ('waived', 'Waived')], default='open', max_length=20),
        ),
    ]
