# Generated by Django 5.2.7 on 2026-06-06 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_signature_url_to_doctor_operator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinvitation',
            name='invited_representative_email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email del representante invitado'),
        ),
        migrations.AddField(
            model_name='patientinvitation',
            name='invited_representative_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del representante invitado'),
        ),
        migrations.AddField(
            model_name='patientinvitation',
            name='invited_representative_relationship',
            field=models.CharField(blank=True, choices=[('father', 'Padre'), ('mother', 'Madre'), ('legal_guardian', 'Tutor Legal'), ('grandfather', 'Abuelo'), ('grandmother', 'Abuela'), ('other', 'Otro')], max_length=20, null=True, verbose_name='Relación del representante'),
        ),
        migrations.AddField(
            model_name='patientinvitation',
            name='is_invitation_for_minor',
            field=models.BooleanField(default=False, help_text='Si es true, la invitación es para el representante del menor', verbose_name='¿Invitación para menor?'),
        ),
        migrations.CreateModel(
            name='DoctorPatientRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('primary_care', 'Médico de Cabecera'), ('consulting', 'Consultante'), ('referred', 'Referido'), ('emergency', 'Emergencia')], default='primary_care', max_length=20, verbose_name='Tipo de relación')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('inactive', 'Inactiva'), ('transferred', 'Transferida')], default='active', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_relationships', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_relationships', to='core.doctoroperator', verbose_name='Doctor')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_patient_relationships', to='core.institutionsettings', verbose_name='Institución')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_relationships', to='core.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Relación Doctor-Paciente',
                'verbose_name_plural': 'Relaciones Doctor-Paciente',
                'db_table': 'doctor_patient_relationships',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['doctor', 'status'], name='doctor_pati_doctor__96bf63_idx'), models.Index(fields=['patient', 'status'], name='doctor_pati_patient_3dfe74_idx'), models.Index(fields=['relationship_type'], name='doctor_pati_relatio_7fc0cb_idx')],
                'unique_together': {('doctor', 'patient', 'relationship_type')},
            },
        ),
        migrations.CreateModel(
            name='PatientFamilyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('self', 'Yo mismo'), ('child', 'Hijo/Hija'), ('dependent', 'Dependiente')], default='child', max_length=20, verbose_name='Tipo de relación')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_links', to='core.patient', verbose_name='Paciente')),
                ('patient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_links', to='core.patientuser', verbose_name='Usuario Paciente (Representante)')),
            ],
            options={
                'verbose_name': 'Vínculo Familiar',
                'verbose_name_plural': 'Vínculos Familiares',
                'db_table': 'patient_family_links',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient_user', 'status'], name='patient_fam_patient_6df5bc_idx'), models.Index(fields=['patient'], name='patient_fam_patient_1a2261_idx')],
                'unique_together': {('patient_user', 'patient')},
            },
        ),
    ]
