# Generated by Django 5.2.7 on 2025-10-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_waitingroomentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitingroomentry',
            options={'ordering': ['order', 'arrival_time'], 'verbose_name': 'Waiting Room Entry', 'verbose_name_plural': 'Waiting Room Entrys'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('arrived', 'Arrived'), ('in_consultation', 'In Consultation'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalappointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('arrived', 'Arrived'), ('in_consultation', 'In Consultation'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
