# Generated by Django 5.2.7 on 2026-03-03 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_patientuser_user_alter_patientuser_password_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Token de invitación')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviada'), ('activated', 'Activada'), ('expired', 'Expirada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de activación')),
                ('expires_at', models.DateTimeField(verbose_name='Fecha de expiración')),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='Referencia del pago')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto pagado')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha del pago')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='core.doctoroperator', verbose_name='Doctor que invita')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_invitations', to='core.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Invitación al Portal',
                'verbose_name_plural': 'Invitaciones al Portal',
                'db_table': 'patient_invitations',
                'ordering': ['-created_at'],
            },
        ),
    ]
