# Generated by Django 5.2.7 on 2026-06-06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_patientinvitation_invited_representative_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="id_type",
            field=models.CharField(
                choices=[
                    ("V", "Venezolano"),
                    ("E", "Extranjero"),
                    ("J", "Jurídico"),
                    ("G", "Gobierno"),
                ],
                default="V",
                max_length=1,
                verbose_name="Tipo de identificación",
            ),
        ),
    ]
