# Generated by Django 5.2.7 on 2026-06-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_id_type_to_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='id_type',
            field=models.CharField(choices=[('V', 'Venezolano'), ('E', 'Extranjero'), ('J', 'Jurídico'), ('G', 'Gobierno')], default='V', max_length=1, verbose_name='Tipo de identificación'),
        ),
    ]
