# Generated by Django 5.2.7 on 2025-10-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_waitingroomentry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitingroomentry',
            options={'ordering': ['order', 'arrival_time'], 'verbose_name': 'Waiting Room Entry', 'verbose_name_plural': 'Waiting Room Entries'},
        ),
        migrations.AlterField(
            model_name='waitingroomentry',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('in_consultation', 'In Consultation'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='waiting', max_length=20),
        ),
    ]
