# Generated by Django 5.2.7 on 2026-03-07 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_patientinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono para Pago Móvil')),
                ('mobile_national_id', models.CharField(blank=True, max_length=20, verbose_name='Cédula para Pago Móvil')),
                ('preferred_bank', models.CharField(blank=True, choices=[('0102', 'BANCO DE VENEZUELA'), ('0104', 'BANCO VENEZOLANO DE CREDITO'), ('0105', 'BANCO MERCANTIL'), ('0108', 'BBVA PROVINCIAL'), ('0114', 'BANCARIBE'), ('0115', 'BANCO EXTERIOR'), ('0128', 'BANCO CARONI'), ('0134', 'BANESCO'), ('0137', 'BANCO SOFITASA'), ('0138', 'BANCO PLAZA'), ('0146', 'BANGENTE'), ('0151', 'BANCO FONDO COMUN'), ('0156', '100% BANCO'), ('0157', 'DELSUR BANCO UNIVERSAL'), ('0163', 'BANCO DEL TESORO'), ('0168', 'BANCRECER'), ('0169', 'R4 BANCO MICROFINANCIERO C.A.'), ('0171', 'BANCO ACTIVO'), ('0172', 'BANCAMIGA BANCO UNIVERSAL'), ('0173', 'BANCO INTERNACIONAL DE DESARROLLO'), ('0174', 'BANPLUS'), ('0175', 'BANCO DIGITAL DE LOS TRABAJADORES'), ('0177', 'BANFANB'), ('0178', 'N58 BANCO DIGITAL'), ('0191', 'BANCO NACIONAL DE CREDITO')], max_length=4, verbose_name='Banco Preferido')),
                ('last_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Último monto pagado (BS)')),
                ('crypto_wallet', models.CharField(blank=True, max_length=100, verbose_name='Wallet Crypto')),
                ('crypto_type', models.CharField(blank=True, choices=[('BTC', 'Bitcoin'), ('USDT', 'USDT (Tether)'), ('ETH', 'Ethereum')], max_length=10, verbose_name='Tipo de Criptomoneda')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_method', to='core.patient')),
            ],
            options={
                'verbose_name': 'Método de Pago del Paciente',
                'verbose_name_plural': 'Métodos de Pago de Pacientes',
            },
        ),
    ]
