# Generated by Django 5.2.7 on 2026-03-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_patientpaymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayment',
            name='amount_ves',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto en Bs (BCV del día)'),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='exchange_rate_bcv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tasa BCV usada'),
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_ves',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto en Bs (BCV del día)'),
        ),
        migrations.AddField(
            model_name='payment',
            name='exchange_rate_bcv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tasa BCV usada'),
        ),
    ]
