# Generated by Django 5.2.7 on 2026-06-08 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_historicalpatient_id_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chargeorder',
            name='responsible_payer',
            field=models.ForeignKey(blank=True, help_text='Para menores: el representante que paga. Para adultos: el mismo paciente. Auto-completado en save() si está vacío.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_charge_orders', to='core.patient', verbose_name='Responsable de pago'),
        ),
        migrations.AddField(
            model_name='historicalchargeorder',
            name='responsible_payer',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Para menores: el representante que paga. Para adultos: el mismo paciente. Auto-completado en save() si está vacío.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.patient', verbose_name='Responsable de pago'),
        ),
        migrations.AddIndex(
            model_name='chargeorder',
            index=models.Index(fields=['responsible_payer', 'status'], name='core_charge_respons_958ca1_idx'),
        ),
    ]
