# Generated by Django 5.2.7 on 2026-03-08 00:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_historicalpayment_amount_ves_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpayment',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='historicalpayment',
            name='charge_order',
        ),
        migrations.RemoveField(
            model_name='historicalpayment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='historicalpayment',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpayment',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='historicalpayment',
            name='received_by',
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='core_paymen_institu_b6d8d6_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='core_paymen_gateway_c878a7_idx',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='cleared_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='gateway_response_raw',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='idempotency_key',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='received_by',
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Referencia bancaria'),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='verification_notes',
            field=models.TextField(blank=True, verbose_name='Notas de verificación'),
        ),
        migrations.AddField(
            model_name='payment',
            name='verification_type',
            field=models.CharField(blank=True, choices=[('automatic', 'Automático'), ('manual', 'Manual')], max_length=20, null=True, verbose_name='Tipo de verificación'),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de verificación'),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='core_paymen_status_6acb70_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['charge_order', 'status'], name='core_paymen_charge__562770_idx'),
        ),
        migrations.DeleteModel(
            name='HistoricalPayment',
        ),
    ]
