# Generated by Django 5.2.7 on 2025-11-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_medicalreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='code',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='foundation_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='icd_code',
            field=models.CharField(default='SIN-CODIGO', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='title',
            field=models.CharField(default='SIN-CODIGO', max_length=255),
            preserve_default=False,
        ),
    ]
