# Generated by Django 5.2.7 on 2026-06-16 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_optimize_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalStatusAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('surgery', 'Cirugía'), ('hospitalization', 'Hospitalización')], max_length=20, verbose_name='Tipo de registro')),
                ('record_id', models.PositiveIntegerField(verbose_name='ID del registro')),
                ('old_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado anterior')),
                ('new_status', models.CharField(max_length=50, verbose_name='Estado nuevo')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas del cambio')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información adicional del cambio')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora del cambio')),
            ],
            options={
                'verbose_name': 'Auditoría de Estado Médico',
                'verbose_name_plural': 'Auditorías de Estados Médicos',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='appt_inst_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='appt_doc_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='appt_pat_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='appt_inst_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='appt_stat_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='appt_doc_service_idx',
        ),
        migrations.RemoveIndex(
            model_name='chargeorder',
            name='co_inst_stat_issued_idx',
        ),
        migrations.RemoveIndex(
            model_name='chargeorder',
            name='co_doc_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='doctorservice',
            name='svc_doc_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='doctorservice',
            name='svc_inst_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='doctorservice',
            name='svc_category_idx',
        ),
        migrations.RemoveIndex(
            model_name='patient',
            name='pat_active_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='patient',
            name='pat_is_minor_idx',
        ),
        migrations.RemoveIndex(
            model_name='patient',
            name='pat_neighborhood_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='pay_inst_stat_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='pay_doc_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='pay_charge_order_idx',
        ),
        migrations.RemoveIndex(
            model_name='serviceschedule',
            name='sch_svc_day_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='serviceschedule',
            name='sch_inst_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='waitingroomentry',
            name='wre_inst_stat_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='waitingroomentry',
            name='wre_patient_idx',
        ),
        migrations.RemoveIndex(
            model_name='waitingroomentry',
            name='wre_appointment_idx',
        ),
        migrations.AddField(
            model_name='hospitalization',
            name='charge_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitalizations', to='core.chargeorder', verbose_name='Orden de cobro asociada'),
        ),
        migrations.AddField(
            model_name='medicalstatusauditlog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por'),
        ),
        migrations.AddField(
            model_name='medicalstatusauditlog',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_audit_logs', to='core.patient', verbose_name='Paciente'),
        ),
        migrations.AddIndex(
            model_name='medicalstatusauditlog',
            index=models.Index(fields=['patient', 'timestamp'], name='core_medica_patient_bfeb6d_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalstatusauditlog',
            index=models.Index(fields=['record_type', 'record_id'], name='core_medica_record__08902a_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalstatusauditlog',
            index=models.Index(fields=['old_status', 'new_status'], name='core_medica_old_sta_d19e39_idx'),
        ),
    ]
