# Generated by Django 5.2.7 on 2026-03-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_payment_created_at_alter_payment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payments/screenshots/%Y/%m/', verbose_name='Captura de pago'),
        ),
    ]
