# Generated by Django 5.2.7 on 2026-06-16 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_charge_order_hospitalization_and_medical_status_audit_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('surgery_scheduled', 'Cirugía Programada'), ('surgery_in_progress', 'Cirugía En Curso'), ('surgery_completed', 'Cirugía Completada'), ('surgery_canceled', 'Cirugía Cancelada'), ('surgery_postponed', 'Cirugía Pospuesta'), ('hospitalization_admitted', 'Hospitalización - Admitido'), ('hospitalization_critical', 'Hospitalización - Estado Crítico'), ('hospitalization_discharged', 'Hospitalización - Dado de Alta'), ('hospitalization_improving', 'Hospitalización - En Mejoría'), ('general', 'Notificación General')], max_length=30, verbose_name='Tipo de notificación')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leída')),
                ('related_record_type', models.CharField(blank=True, choices=[('surgery', 'Cirugía'), ('hospitalization', 'Hospitalización')], max_length=20, null=True, verbose_name='Tipo de registro relacionado')),
                ('related_record_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID del registro relacionado')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos adicionales de la notificación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Notificación de Paciente',
                'verbose_name_plural': 'Notificaciones de Pacientes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'is_read', '-created_at'], name='core_patien_patient_89ff3d_idx'), models.Index(fields=['notification_type', '-created_at'], name='core_patien_notific_6c28cb_idx')],
            },
        ),
    ]
