# Generated by Django 5.2.7 on 2025-11-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_diagnosis_code_diagnosis_foundation_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICD11UpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('added', models.IntegerField(default=0)),
                ('updated', models.IntegerField(default=0)),
                ('removed', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ICD-11 update log',
                'verbose_name_plural': 'ICD-11 update logs',
            },
        ),
        migrations.CreateModel(
            name='ICD11Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icd_code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('foundation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('definition', models.TextField(blank=True, null=True)),
                ('synonyms', models.JSONField(blank=True, null=True)),
                ('parent_code', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'ICD-11 entry',
                'verbose_name_plural': 'ICD-11 entries',
                'indexes': [models.Index(fields=['icd_code'], name='core_icd11e_icd_cod_a8ea47_idx'), models.Index(fields=['title'], name='core_icd11e_title_5ccbe2_idx')],
            },
        ),
    ]
