# Generated by Django 5.2.7 on 2026-03-12 00:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_payment_screenshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text='Nombre del icono para UI', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría de Servicio',
                'verbose_name_plural': 'Categorías de Servicios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_ves', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_visible_global', models.BooleanField(default=True, help_text='Si es True, aparece en el catálogo global')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.doctoroperator')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_services', to='core.institutionsettings')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.servicecategory')),
            ],
            options={
                'verbose_name': 'Servicio del Doctor',
                'verbose_name_plural': 'Servicios de Doctores',
                'ordering': ['doctor', 'name'],
                'unique_together': {('doctor', 'name', 'institution')},
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='core.doctorservice', verbose_name='Servicio específico agendado'),
        ),
        migrations.AddField(
            model_name='chargeitem',
            name='doctor_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge_items', to='core.doctorservice', verbose_name='Servicio facturado'),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='doctor_service',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.doctorservice', verbose_name='Servicio específico agendado'),
        ),
    ]
