# Generated by Django 5.2.7 on 2026-06-18 23:25

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_patient_notification_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMedicalCalculation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('calculator_id', models.CharField(choices=[('bmi', 'IMC'), ('bsa', 'BSA (Mosteller)'), ('cha2ds2_vasc', 'CHA₂DS₂-VASc'), ('has_bled', 'HAS-BLED'), ('ckd_epi', 'CKD-EPI 2021'), ('gcs', 'GCS'), ('qsofa', 'qSOFA'), ('wells_pe', 'Wells EP')], max_length=20, verbose_name='Calculadora')),
                ('calculator_name', models.CharField(max_length=100, verbose_name='Nombre de calculadora')),
                ('inputs', models.JSONField(verbose_name='Parámetros de entrada')),
                ('result_value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Valor del resultado')),
                ('result_unit', models.CharField(blank=True, max_length=30, null=True, verbose_name='Unidad')),
                ('interpretation', models.TextField(blank=True, null=True, verbose_name='Interpretación')),
                ('risk_level', models.CharField(blank=True, choices=[('Bajo', 'Bajo'), ('Bajo-Moderado', 'Bajo-Moderado'), ('Moderado', 'Moderado'), ('Moderado-Alto', 'Moderado-Alto'), ('Alto', 'Alto'), ('Muy alto', 'Muy alto'), ('Extremadamente alto', 'Extremadamente alto'), ('Óptimo', 'Óptimo')], max_length=20, null=True, verbose_name='Nivel de riesgo')),
                ('result_details', models.JSONField(blank=True, null=True, verbose_name='Detalles del resultado')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas clínicas')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Última modificación')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('doctor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Médico solicitante')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'historical Cálculo Médico',
                'verbose_name_plural': 'historical Cálculos Médicos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MedicalCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculator_id', models.CharField(choices=[('bmi', 'IMC'), ('bsa', 'BSA (Mosteller)'), ('cha2ds2_vasc', 'CHA₂DS₂-VASc'), ('has_bled', 'HAS-BLED'), ('ckd_epi', 'CKD-EPI 2021'), ('gcs', 'GCS'), ('qsofa', 'qSOFA'), ('wells_pe', 'Wells EP')], max_length=20, verbose_name='Calculadora')),
                ('calculator_name', models.CharField(max_length=100, verbose_name='Nombre de calculadora')),
                ('inputs', models.JSONField(verbose_name='Parámetros de entrada')),
                ('result_value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Valor del resultado')),
                ('result_unit', models.CharField(blank=True, max_length=30, null=True, verbose_name='Unidad')),
                ('interpretation', models.TextField(blank=True, null=True, verbose_name='Interpretación')),
                ('risk_level', models.CharField(blank=True, choices=[('Bajo', 'Bajo'), ('Bajo-Moderado', 'Bajo-Moderado'), ('Moderado', 'Moderado'), ('Moderado-Alto', 'Moderado-Alto'), ('Alto', 'Alto'), ('Muy alto', 'Muy alto'), ('Extremadamente alto', 'Extremadamente alto'), ('Óptimo', 'Óptimo')], max_length=20, null=True, verbose_name='Nivel de riesgo')),
                ('result_details', models.JSONField(blank=True, null=True, verbose_name='Detalles del resultado')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas clínicas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_calculations', to=settings.AUTH_USER_MODEL, verbose_name='Médico solicitante')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_calculations', to='core.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Cálculo Médico',
                'verbose_name_plural': 'Cálculos Médicos',
                'db_table': 'medical_calculations',
                'ordering': ['-created_at'],
            },
        ),
    ]
