# Generated by Django 5.2.7 on 2026-03-12 19:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_servicecategory_doctorservice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='historicalbillingitem',
            name='category',
        ),
        migrations.AlterUniqueTogether(
            name='billingitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='billingitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='billingitem',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='historicalbillingitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalbillingitem',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalbillingitem',
            name='institution',
        ),
        migrations.AlterUniqueTogether(
            name='doctorservice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='doctorservice',
            name='code',
            field=models.CharField(default='SVC-TEMP', help_text='Código único del servicio (ej: CONS-001)', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorservice',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio base en dólares (USD)', max_digits=10),
        ),
        migrations.DeleteModel(
            name='BillingCategory',
        ),
        migrations.DeleteModel(
            name='BillingItem',
        ),
        migrations.DeleteModel(
            name='HistoricalBillingItem',
        ),
        migrations.RemoveField(
            model_name='doctorservice',
            name='price_ves',
        ),
    ]
