# Generated by Django 5.2.7 on 2026-06-19 01:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_medical_calculation_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldocument',
            name='contains_phi',
            field=models.BooleanField(default=True, help_text='Contiene Protected Health Information'),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA256 para deduplicación de archivos', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='is_clinical_research',
            field=models.BooleanField(default=False, help_text='Marcado para investigación clínica agregada'),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='is_diagnostic_analysis',
            field=models.BooleanField(default=False, help_text='Marcado por Centro de Diagnóstico Inteligente (OCR/calculadoras)'),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='ocr_confidence_score',
            field=models.FloatField(blank=True, help_text='Confianza promedio del OCR (0-1)', null=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='ocr_extracted_text',
            field=models.TextField(blank=True, help_text='Texto extraído por OCR (solo visible para médico)', null=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='ocr_processed_at',
            field=models.DateTimeField(blank=True, help_text='Última vez que se ejecutó OCR', null=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='parsed_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Valores estructurados extraídos: lab values, dates, names'),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='visibility',
            field=models.CharField(choices=[('doctor_only', 'Solo Médico'), ('doctor_institution', 'Médico + Institución'), ('patient_visible', 'Visible para Paciente'), ('public', 'Compartido')], db_index=True, default='patient_visible', help_text='Controla visibilidad entre Doctor y Patient Portal', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='category',
            field=models.CharField(choices=[('prescription', 'Prescripción'), ('treatment', 'Tratamiento'), ('medical_test_order', 'Órdenes de Exámenes'), ('medical_referral', 'Referencia Médica'), ('medical_report', 'Informe Médico General'), ('external_study', 'Estudio Externo (Laboratorio/Imagen)'), ('lab_result', 'Resultado de Laboratorio'), ('imaging_report', 'Reporte de Imagen'), ('diagnostic_analysis', 'Análisis Diagnóstico'), ('other', 'Otro')], default='other', max_length=40),
        ),
        migrations.AddIndex(
            model_name='medicaldocument',
            index=models.Index(fields=['visibility'], name='core_medica_visibil_e6438a_idx'),
        ),
        migrations.AddIndex(
            model_name='medicaldocument',
            index=models.Index(fields=['is_diagnostic_analysis'], name='core_medica_is_diag_8cc823_idx'),
        ),
    ]
