# Generated by Django 5.2.7 on 2025-11-12 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_medicalreferral_medicaltest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalreferral',
            options={'verbose_name': 'Medical Referral', 'verbose_name_plural': 'Medical Referrals'},
        ),
        migrations.AlterModelOptions(
            name='medicaltest',
            options={'verbose_name': 'Medical Test', 'verbose_name_plural': 'Medical Tests'},
        ),
        migrations.RemoveField(
            model_name='medicalreferral',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='medicalreferral',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='medicalreferral',
            name='issued_at',
        ),
        migrations.RemoveField(
            model_name='medicalreferral',
            name='issued_by',
        ),
        migrations.RemoveField(
            model_name='medicalreferral',
            name='referred_to',
        ),
        migrations.RemoveField(
            model_name='medicalreferral',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='medicalreferral',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='medicaltest',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='medicaltest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='medicaltest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='medicaltest',
            name='requested_at',
        ),
        migrations.RemoveField(
            model_name='medicaltest',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='medicaltest',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='medicaltest',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='medicalreferral',
            name='specialty',
            field=models.CharField(
                choices=[
                    ('allergy_immunology', 'Allergy and Immunology (Alergia e Inmunología)'),
                    ('anesthesiology', 'Anesthesiology (Anestesiología)'),
                    ('cardiology', 'Cardiology (Cardiología)'),
                    ('dermatology', 'Dermatology (Dermatología)'),
                    ('diagnostic_radiology', 'Diagnostic Radiology (Radiología Diagnóstica)'),
                    ('emergency_medicine', 'Emergency Medicine (Medicina de Emergencia/Urgencias)'),
                    ('endocrinology', 'Endocrinology (Endocrinología)'),
                    ('family_medicine', 'Family Medicine (Medicina Familiar)'),
                    ('gastroenterology', 'Gastroenterology (Gastroenterología)'),
                    ('general_surgery', 'General Surgery (Cirugía General)'),
                    ('geriatrics', 'Geriatric Medicine (Medicina Geriátrica/Geriatría)'),
                    ('hematology', 'Hematology (Hematología)'),
                    ('infectious_disease', 'Infectious Disease (Enfermedades Infecciosas)'),
                    ('internal_medicine', 'Internal Medicine (Medicina Interna)'),
                    ('nephrology', 'Nephrology (Nefrología)'),
                    ('neurology', 'Neurology (Neurología)'),
                    ('neurosurgery', 'Neurosurgery (Neurocirugía)'),
                    ('nuclear_medicine', 'Nuclear Medicine (Medicina Nuclear)'),
                    ('obgyn', 'Obstetrics and Gynecology (Obstetricia y Ginecología)'),
                    ('ophthalmology', 'Ophthalmology (Oftalmología)'),
                    ('orthopedic_surgery', 'Orthopedic Surgery (Cirugía Ortopédica/Traumatología)'),
                    ('otolaryngology', 'Otolaryngology (Otorrinolaringología)'),
                    ('pathology', 'Pathology (Patología)'),
                    ('pediatrics', 'Pediatrics (Pediatría)'),
                    ('pmr', 'Physical Medicine and Rehabilitation (Medicina Física y Rehabilitación)'),
                    ('plastic_surgery', 'Plastic Surgery (Cirugía Plástica)'),
                    ('preventive_medicine', 'Preventive Medicine (Medicina Preventiva)'),
                    ('psychiatry', 'Psychiatry (Psiquiatría)'),
                    ('pulmonology', 'Pulmonary Disease (Enfermedad Pulmonar/Neumología)'),
                    ('radiation_oncology', 'Radiation Oncology (Oncología Radioterápica)'),
                    ('rheumatology', 'Rheumatology (Reumatología)'),
                    ('urology', 'Urology (Urología)'),
                    ('vascular_surgery', 'Vascular Surgery (Cirugía Vascular)'),
                    ('other', 'Other (Otro)')
                ],
                max_length=50,
                default="other"   # ✅ dejamos el default explícito
            ),
        ),
        migrations.AddField(
            model_name='medicalreferral',
            name='urgency',
            field=models.CharField(choices=[('routine', 'Rutina'), ('priority', 'Prioridad'), ('urgent', 'Urgente')], default='routine', max_length=20),
        ),
        migrations.AddField(
            model_name='medicaltest',
            name='urgency',
            field=models.CharField(choices=[('routine', 'Rutina'), ('priority', 'Prioridad'), ('urgent', 'Urgente')], default='routine', max_length=20),
        ),
        migrations.AddField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Diaria'), ('bid', 'Dos veces al día'), ('tid', 'Tres veces al día'), ('qhs', 'Antes de dormir'), ('prn', 'Según necesidad')], default='daily', max_length=20),
        ),
        migrations.AddField(
            model_name='prescription',
            name='route',
            field=models.CharField(choices=[('oral', 'Oral'), ('iv', 'Intravenosa'), ('im', 'Intramuscular'), ('topical', 'Tópica'), ('other', 'Otro')], default='oral', max_length=20),
        ),
        migrations.AddField(
            model_name='prescription',
            name='unit',
            field=models.CharField(choices=[('mg', 'Miligramos'), ('ml', 'Mililitros'), ('tablet', 'Tableta'), ('capsule', 'Cápsula'), ('drop', 'Gotas')], default='mg', max_length=20),
        ),
        migrations.AddField(
            model_name='treatment',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='treatment',
            name='treatment_type',
            field=models.CharField(choices=[('pharmacological', 'Farmacológico'), ('surgical', 'Quirúrgico'), ('rehabilitation', 'Rehabilitación'), ('lifestyle', 'Cambio de estilo de vida'), ('other', 'Otro')], default='pharmacological', max_length=30),
        ),
        migrations.AlterField(
            model_name='medicalreferral',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='core.appointment'),
        ),
        migrations.AlterField(
            model_name='medicalreferral',
            name='diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='core.diagnosis'),
        ),
        migrations.AlterField(
            model_name='medicalreferral',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='medicalreferral',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicaltest',
            name='test_type',
            field=models.CharField(choices=[('blood_test', 'Análisis de sangre'), ('urine_test', 'Análisis de orina'), ('biopsy', 'Biopsia'), ('genetic_test', 'Prueba genética'), ('microbiology_culture', 'Cultivo microbiológico'), ('xray', 'Rayos X / Radiografía'), ('ultrasound', 'Ecografía'), ('ct_scan', 'Tomografía computarizada (TC)'), ('mri', 'Resonancia magnética (RM)'), ('ecg', 'Electrocardiograma')], max_length=50),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dosage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
