# Generated by Django 5.2.7 on 2025-11-12 20:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_medicalreferral_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldocument',
            name='checksum_sha256',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='is_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='mime_type',
            field=models.CharField(default='application/pdf', max_length=100),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='origin_panel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='signer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='signer_registration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='size_bytes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='source',
            field=models.CharField(choices=[('system_generated', 'Generado por el sistema'), ('user_uploaded', 'Subido por usuario')], default='system_generated', max_length=20),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='storage_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='template_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='category',
            field=models.CharField(choices=[('prescription', 'Prescripción'), ('treatment', 'Tratamiento'), ('medical_test_order', 'Órdenes de Exámenes'), ('medical_referral', 'Referencia Médica'), ('medical_report', 'Informe Médico General'), ('other', 'Otro')], default='other', max_length=40),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='file',
            field=models.FileField(upload_to='medical_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='medicaldocument',
            index=models.Index(fields=['patient', 'appointment', 'category'], name='core_medica_patient_6ed362_idx'),
        ),
        migrations.AddIndex(
            model_name='medicaldocument',
            index=models.Index(fields=['category', 'template_version'], name='core_medica_categor_3d7cff_idx'),
        ),
        migrations.AddIndex(
            model_name='medicaldocument',
            index=models.Index(fields=['uploaded_at'], name='core_medica_uploade_4b1958_idx'),
        ),
    ]
