# Generated by Django 5.2.7 on 2026-03-15 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_servicecategory_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoroperator',
            name='bio',
            field=models.TextField(blank=True, help_text='Biografía corta del doctor para el perfil público', null=True),
        ),
        migrations.AddField(
            model_name='doctoroperator',
            name='photo_url',
            field=models.CharField(blank=True, help_text='URL de foto de perfil del doctor', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicaldoctoroperator',
            name='bio',
            field=models.TextField(blank=True, help_text='Biografía corta del doctor para el perfil público', null=True),
        ),
        migrations.AddField(
            model_name='historicaldoctoroperator',
            name='photo_url',
            field=models.CharField(blank=True, help_text='URL de foto de perfil del doctor', max_length=500, null=True),
        ),
    ]
