# Generated by Django 5.2.7 on 2025-11-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_medicaldocument_checksum_sha256_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Specialty',
                'verbose_name_plural': 'Specialties',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='doctoroperator',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='medicalreferral',
            name='specialty',
        ),
        migrations.AddField(
            model_name='doctoroperator',
            name='specialties',
            field=models.ManyToManyField(related_name='doctors', to='core.specialty'),
        ),
        migrations.AddField(
            model_name='medicalreferral',
            name='specialties',
            field=models.ManyToManyField(related_name='referrals', to='core.specialty'),
        ),
    ]
