# Generated by Django 5.2.7 on 2026-03-15 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_doctoroperator_bio_doctoroperator_photo_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargeorder',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charge_orders', to='core.appointment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.appointment'),
        ),
    ]
