# Generated by Django 5.2.7 on 2025-11-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_load_specialties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreferral',
            name='status',
            field=models.CharField(choices=[('issued', 'Emitida'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada')], default='issued', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicalreferral',
            name='urgency',
            field=models.CharField(choices=[('routine', 'Rutina'), ('urgent', 'Urgente'), ('stat', 'Inmediato (STAT)')], default='routine', max_length=20),
        ),
    ]
