# Generated by Django 5.2.7 on 2026-03-16 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_chargeorder_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorservice',
            name='booking_lead_time',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='doctorservice',
            name='cancellation_window',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='doctorservice',
            name='requires_appointment',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ServiceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_duration', models.IntegerField(default=30)),
                ('max_appointments', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_schedules', to='core.institutionsettings')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.doctorservice')),
            ],
            options={
                'verbose_name': 'Horario de Servicio',
                'verbose_name_plural': 'Horarios de Servicios',
                'unique_together': {('service', 'institution', 'day_of_week', 'start_time')},
            },
        ),
    ]
