# Generated by Django 5.2.7 on 2026-03-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_doctorservice_booking_lead_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de confirmación'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='tentative_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha tentativa seleccionada'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='tentative_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora tentativa seleccionada'),
        ),
        migrations.AddField(
            model_name='chargeorder',
            name='tentative_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha tentativa seleccionada por paciente'),
        ),
        migrations.AddField(
            model_name='chargeorder',
            name='tentative_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora tentativa seleccionada por paciente'),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de confirmación'),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='tentative_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha tentativa seleccionada'),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='tentative_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora tentativa seleccionada'),
        ),
        migrations.AddField(
            model_name='historicalchargeorder',
            name='tentative_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha tentativa seleccionada por paciente'),
        ),
        migrations.AddField(
            model_name='historicalchargeorder',
            name='tentative_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora tentativa seleccionada por paciente'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('tentative', 'Tentativa'), ('arrived', 'Arrived'), ('in_consultation', 'In Consultation'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('rejected', 'Rechazada')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctorservice',
            name='booking_lead_time',
            field=models.IntegerField(default=24, help_text='Horas de anticipación requeridas para agendar una cita', verbose_name='Horas mínimas para agendar'),
        ),
        migrations.AlterField(
            model_name='doctorservice',
            name='cancellation_window',
            field=models.IntegerField(default=24, help_text='Horas de anticipación requeridas para cancelar una cita sin penalización', verbose_name='Horas mínimas para cancelar'),
        ),
        migrations.AlterField(
            model_name='doctorservice',
            name='requires_appointment',
            field=models.BooleanField(default=True, verbose_name='Requiere cita previa'),
        ),
        migrations.AlterField(
            model_name='historicalappointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('tentative', 'Tentativa'), ('arrived', 'Arrived'), ('in_consultation', 'In Consultation'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('rejected', 'Rechazada')], default='pending', max_length=20),
        ),
    ]
