# Generated by Django 5.2.7 on 2025-11-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_medicalreferral_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreferral',
            name='referred_to',
            field=models.CharField(blank=True, help_text='Nombre del doctor o servicio al que se refiere', max_length=255, null=True),
        ),
    ]
