# Generated by Django 5.2.7 on 2025-11-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_medicalreferral_referred_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(choices=[('once_daily', 'Una vez al día'), ('bid', 'Dos veces al día'), ('tid', 'Tres veces al día'), ('qid', 'Cuatro veces al día'), ('q4h', 'Cada 4 horas'), ('q6h', 'Cada 6 horas'), ('q8h', 'Cada 8 horas'), ('q12h', 'Cada 12 horas'), ('q24h', 'Cada 24 horas'), ('qod', 'Día por medio'), ('stat', 'Una sola vez / Inmediato'), ('prn', 'Según necesidad'), ('hs', 'Al acostarse'), ('ac', 'Antes de las comidas'), ('pc', 'Después de las comidas'), ('achs', 'Antes de comidas y al acostarse')], default='once_daily', max_length=20),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='route',
            field=models.CharField(choices=[('oral', 'Oral'), ('iv', 'Intravenosa'), ('im', 'Intramuscular'), ('topical', 'Tópica'), ('sublingual', 'Sublingual'), ('inhalation', 'Inhalación'), ('rectal', 'Rectal'), ('other', 'Otro')], default='oral', max_length=20),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='unit',
            field=models.CharField(choices=[('mg', 'Miligramos'), ('ml', 'Mililitros'), ('tablet', 'Tableta'), ('capsule', 'Cápsula'), ('drop', 'Gotas'), ('puff', 'Inhalación'), ('unit', 'Unidad'), ('patch', 'Parche')], default='mg', max_length=20),
        ),
    ]
