# Generated by Django 5.2.7 on 2026-03-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_appointment_confirmed_at_appointment_tentative_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='category_type',
            field=models.CharField(choices=[('APPOINTMENT', 'Consulta/Cita'), ('PROCEDURE', 'Procedimiento Médico'), ('DIAGNOSTIC', 'Diagnóstico/Laboratorio'), ('PHARMACY', 'Farmacia/Medicamento'), ('PACKAGE', 'Paquete/Promoción'), ('ADMIN', 'Servicio Administrativo')], default='ADMIN', max_length=20, verbose_name='Tipo de Categoría'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
