# Generated by Django 5.2.7 on 2025-11-14 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_prescription_frequency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='medication',
        ),
        migrations.AddField(
            model_name='prescription',
            name='medication_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='route',
            field=models.CharField(choices=[('oral', 'Oral'), ('iv', 'Intravenosa'), ('im', 'Intramuscular'), ('sc', 'Subcutánea'), ('topical', 'Tópica'), ('sublingual', 'Sublingual'), ('inhalation', 'Inhalación'), ('rectal', 'Rectal'), ('other', 'Otro')], default='oral', max_length=20),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='unit',
            field=models.CharField(choices=[('mg', 'Miligramos'), ('ml', 'Mililitros'), ('g', 'Gramos'), ('tablet', 'Tableta'), ('capsule', 'Cápsula'), ('drop', 'Gotas'), ('puff', 'Inhalación'), ('unit', 'Unidad'), ('patch', 'Parche')], default='mg', max_length=20),
        ),
        migrations.CreateModel(
            name='MedicationCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('presentation', models.CharField(choices=[('tablet', 'Tableta'), ('capsule', 'Cápsula'), ('syrup', 'Jarabe'), ('drop', 'Gotas'), ('injection', 'Inyectable'), ('cream', 'Crema'), ('gel', 'Gel'), ('patch', 'Parche'), ('spray', 'Spray'), ('other', 'Otro')], max_length=50)),
                ('concentration', models.CharField(max_length=100)),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('iv', 'Intravenosa'), ('im', 'Intramuscular'), ('sc', 'Subcutánea'), ('topical', 'Tópica'), ('sublingual', 'Sublingual'), ('inhalation', 'Inhalación'), ('rectal', 'Rectal'), ('other', 'Otro')], max_length=20)),
                ('unit', models.CharField(choices=[('mg', 'Miligramos'), ('ml', 'Mililitros'), ('g', 'Gramos'), ('tablet', 'Tableta'), ('capsule', 'Cápsula'), ('drop', 'Gotas'), ('puff', 'Inhalación'), ('unit', 'Unidad'), ('patch', 'Parche')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Catálogo de Medicamentos',
                'ordering': ['name', 'presentation'],
                'unique_together': {('name', 'presentation', 'concentration')},
            },
        ),
        migrations.AddField(
            model_name='prescription',
            name='medication_catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='core.medicationcatalog'),
        ),
    ]
