# Generated by Django 5.2.7 on 2025-11-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_prescription_medication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargeitem',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
