# Generated by Django 5.2.7 on 2026-03-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_payment_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ocr_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Datos extraídos por OCR'),
        ),
        migrations.AddField(
            model_name='payment',
            name='sender_bank_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código banco del emisor'),
        ),
        migrations.AddField(
            model_name='payment',
            name='sender_national_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula del emisor'),
        ),
        migrations.AddField(
            model_name='payment',
            name='sender_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del emisor'),
        ),
    ]
