# Generated by Django 5.2.7 on 2025-11-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_chargeitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldocument',
            name='audit_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
