# Generated by Django 5.2.7 on 2026-03-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_payment_ocr_data_payment_sender_bank_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoroperator',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='historicaldoctoroperator',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='doctoroperator',
            name='photo',
            field=models.ImageField(blank=True, help_text='Foto de perfil del doctor', null=True, upload_to='doctor_photos/'),
        ),
        migrations.AddField(
            model_name='historicaldoctoroperator',
            name='photo',
            field=models.TextField(blank=True, help_text='Foto de perfil del doctor', max_length=100, null=True),
        ),
    ]
