# Generated by Django 5.2.7 on 2025-11-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_medicaldocument_audit_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
