# Generated by Django 5.2.7 on 2026-04-05 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_doctoroperator_photo_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surgery',
            options={'ordering': ['-scheduled_date'], 'verbose_name': 'Cirugía', 'verbose_name_plural': 'Cirugías'},
        ),
        migrations.RemoveField(
            model_name='surgery',
            name='date',
        ),
        migrations.AddField(
            model_name='surgery',
            name='anesthesia_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surgery',
            name='anesthesia_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surgery',
            name='anesthesia_type',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('regional', 'Regional'), ('local', 'Local'), ('sedation', 'Sedación Consciente'), ('combined', 'Combinada')], max_length=30, null=True, verbose_name='Tipo de anestesia'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='anesthesiologist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgeries_anesthetized', to='core.doctoroperator', verbose_name='Anestesiólogo'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgery', to='core.appointment', verbose_name='Cita asociada'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='asa_classification',
            field=models.CharField(blank=True, choices=[('I', 'ASA I - Paciente sano'), ('II', 'ASA II - Enfermedad sistémica leve'), ('III', 'ASA III - Enfermedad sistémica severa'), ('IV', 'ASA IV - Enfermedad que amenaza la vida'), ('V', 'ASA V - Paciente moribundo'), ('VI', 'ASA VI - Muerte cerebral declarada')], max_length=3, null=True, verbose_name='Clasificación ASA'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='assistants',
            field=models.ManyToManyField(blank=True, related_name='surgeries_assisted', to='core.doctoroperator', verbose_name='Asistentes'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='diagnosis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.diagnosis', verbose_name='Diagnóstico que motiva la cirugía'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='estimated_blood_loss',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Pérdida sanguínea estimada (ml)'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='findings',
            field=models.TextField(blank=True, null=True, verbose_name='Hallazgos quirúrgicos'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de seguimiento'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='surgeries', to='core.institutionsettings'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='post_op_instructions',
            field=models.TextField(blank=True, null=True, verbose_name='Instrucciones post-operatorias'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='procedure_description',
            field=models.TextField(blank=True, default='', verbose_name='Descripción del procedimiento'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Bajo Riesgo'), ('moderate', 'Riesgo Moderado'), ('high', 'Alto Riesgo'), ('critical', 'Crítico')], default='moderate', max_length=20),
        ),
        migrations.AddField(
            model_name='surgery',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha programada'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora programada'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.specialty', verbose_name='Especialidad quirúrgica'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='specimens',
            field=models.TextField(blank=True, null=True, verbose_name='Muestras enviadas a patología'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Programada'), ('pre_op', 'En Pre-operatorio'), ('in_progress', 'En Curso'), ('completed', 'Completada'), ('canceled', 'Cancelada'), ('postponed', 'Pospuesta')], default='scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='surgery',
            name='surgeon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='surgeries_performed', to='core.doctoroperator', verbose_name='Cirujano principal'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='surgery_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surgery',
            name='surgery_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surgery',
            name='surgery_type',
            field=models.CharField(choices=[('elective', 'Electiva / Programada'), ('emergency', 'Emergencia'), ('ambulatory', 'Ambulatoria'), ('minimally_invasive', 'Mínimamente Invasiva'), ('open', 'Cirugía Abierta'), ('robotic', 'Robótica / Asistida')], default='elective', max_length=30),
        ),
        migrations.AddField(
            model_name='surgery',
            name='surgical_technique',
            field=models.TextField(blank=True, null=True, verbose_name='Técnica quirúrgica'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='complications',
            field=models.TextField(blank=True, null=True, verbose_name='Complicaciones'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nombre del procedimiento'),
        ),
        migrations.CreateModel(
            name='Hospitalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_type', models.CharField(choices=[('emergency', 'Emergencia'), ('scheduled', 'Programada'), ('transfer', 'Transferencia'), ('observation', 'Observación')], default='emergency', max_length=20)),
                ('status', models.CharField(choices=[('admitted', 'Admitido'), ('stable', 'Estable'), ('critical', 'Crítico'), ('improving', 'En Mejoría'), ('awaiting_discharge', 'Esperando Alta'), ('discharged', 'Dado de Alta'), ('transferred', 'Transferido'), ('deceased', 'Fallecido')], default='admitted', max_length=20)),
                ('ward', models.CharField(max_length=100, verbose_name='Pabellón / Sala')),
                ('room_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de habitación')),
                ('bed_number', models.CharField(max_length=20, verbose_name='Número de cama')),
                ('admission_date', models.DateTimeField(verbose_name='Fecha de ingreso')),
                ('expected_discharge_date', models.DateField(blank=True, null=True, verbose_name='Fecha estimada de alta')),
                ('actual_discharge_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha real de alta')),
                ('chief_complaint', models.TextField(verbose_name='Motivo principal de ingreso')),
                ('clinical_summary', models.TextField(blank=True, null=True, verbose_name='Resumen clínico')),
                ('vital_signs', models.JSONField(blank=True, null=True, verbose_name='Signos vitales (último registro)')),
                ('allergies_at_admission', models.TextField(blank=True, null=True, verbose_name='Alergias al ingreso')),
                ('daily_notes', models.TextField(blank=True, null=True, verbose_name='Notas de evolución')),
                ('complications', models.TextField(blank=True, null=True, verbose_name='Complicaciones durante estancia')),
                ('discharge_type', models.CharField(blank=True, choices=[('voluntary', 'Alta Voluntaria'), ('medical', 'Alta Médica'), ('transfer', 'Transferencia'), ('deceased', 'Fallecimiento'), ('against_advice', 'Alta contra consejo médico')], max_length=20, null=True, verbose_name='Tipo de egreso')),
                ('discharge_summary', models.TextField(blank=True, null=True, verbose_name='Resumen de alta')),
                ('discharge_instructions', models.TextField(blank=True, null=True, verbose_name='Indicaciones al alta')),
                ('discharge_medications', models.TextField(blank=True, null=True, verbose_name='Medicamentos al alta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission_diagnosis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitalizations', to='core.diagnosis', verbose_name='Diagnóstico de ingreso')),
                ('attending_doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospitalizations_attended', to='core.doctoroperator', verbose_name='Médico tratante')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospitalizations', to='core.institutionsettings')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitalizations', to='core.patient')),
            ],
            options={
                'verbose_name': 'Hospitalización',
                'verbose_name_plural': 'Hospitalizaciones',
                'ordering': ['-admission_date'],
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward', models.CharField(max_length=100, verbose_name='Pabellón / Sala')),
                ('room_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de habitación')),
                ('bed_number', models.CharField(max_length=20, verbose_name='Número de cama')),
                ('bed_type', models.CharField(choices=[('general', 'Cama General'), ('icu', 'UCI'), ('pediatric', 'Pediátrica'), ('isolation', 'Aislamiento'), ('maternity', 'Maternidad')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('occupied', 'Ocupada'), ('maintenance', 'En Mantenimiento'), ('reserved', 'Reservada')], default='available', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='core.institutionsettings')),
            ],
            options={
                'verbose_name': 'Cama',
                'verbose_name_plural': 'Camas',
                'ordering': ['ward', 'room_number', 'bed_number'],
                'unique_together': {('institution', 'bed_number')},
            },
        ),
    ]
