# Generated by Django 5.2.7 on 2026-04-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_surgery_options_remove_surgery_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnomedUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('added', models.IntegerField(default=0)),
                ('updated', models.IntegerField(default=0)),
                ('removed', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'SNOMED CT update log',
                'verbose_name_plural': 'SNOMED CT update logs',
            },
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='catalog',
            field=models.CharField(choices=[('icd11', 'CIE-11 (OMS)'), ('snomed', 'SNOMED CT')], default='icd11', max_length=10, verbose_name='Catálogo de codificación'),
        ),
        migrations.AddField(
            model_name='historicaldiagnosis',
            name='catalog',
            field=models.CharField(choices=[('icd11', 'CIE-11 (OMS)'), ('snomed', 'SNOMED CT')], default='icd11', max_length=10, verbose_name='Catálogo de codificación'),
        ),
        migrations.CreateModel(
            name='SnomedEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_id', models.CharField(max_length=20, unique=True, verbose_name='Concept ID')),
                ('term', models.CharField(max_length=500, verbose_name='Término preferido')),
                ('definition', models.TextField(blank=True, null=True, verbose_name='Definición')),
                ('semantic_tag', models.CharField(blank=True, max_length=100, null=True, verbose_name='Semantic Tag')),
                ('hierarchy', models.CharField(blank=True, max_length=200, null=True, verbose_name='Jerarquía completa')),
                ('parent_concept_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='Concepto padre')),
                ('synonyms', models.JSONField(blank=True, null=True, verbose_name='Sinónimos')),
                ('language', models.CharField(default='es', max_length=5, verbose_name='Idioma')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'SNOMED CT entry',
                'verbose_name_plural': 'SNOMED CT entries',
                'indexes': [models.Index(fields=['concept_id'], name='core_snomed_concept_c973ae_idx'), models.Index(fields=['term'], name='core_snomed_term_a440d5_idx'), models.Index(fields=['semantic_tag'], name='core_snomed_semanti_f32b2d_idx')],
            },
        ),
    ]
