# Generated by Django 5.2.7 on 2025-11-23 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_appointment_completed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='unit',
        ),
        migrations.CreateModel(
            name='PrescriptionComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substance', models.CharField(max_length=100)),
                ('dosage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('mg', 'Miligramos'), ('ml', 'Mililitros'), ('g', 'Gramos'), ('tablet', 'Tableta'), ('capsule', 'Cápsula'), ('drop', 'Gotas'), ('puff', 'Inhalación'), ('unit', 'Unidad'), ('patch', 'Parche')], default='mg', max_length=20)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='core.prescription')),
            ],
        ),
    ]
