# Generated by Django 5.2.7 on 2026-04-06 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_snomedupdatelog_diagnosis_catalog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalization',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitalizations', to='core.bed', verbose_name='Cama asignada'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='charge_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgeries', to='core.chargeorder', verbose_name='Orden de cobro asociada'),
        ),
    ]
