# Generated by Django 5.2.7 on 2025-11-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_prescription_dosage_remove_prescription_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaltest',
            name='test_type',
            field=models.CharField(choices=[('blood_test', 'Análisis de sangre'), ('urine_test', 'Análisis de orina'), ('stool_test', 'Análisis de heces'), ('biopsy', 'Biopsia'), ('genetic_test', 'Prueba genética'), ('microbiology_culture', 'Cultivo microbiológico'), ('xray', 'Rayos X / Radiografía'), ('ultrasound', 'Ecografía'), ('ct_scan', 'Tomografía computarizada (TC)'), ('mri', 'Resonancia magnética (RM)'), ('ecg', 'Electrocardiograma')], max_length=50),
        ),
    ]
