# Generated by Django 5.2.7 on 2025-12-17 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_medicaltest_test_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('country', models.CharField(default='Venezuela', max_length=100)),
            ],
            options={
                'verbose_name': 'Vaccine',
                'verbose_name_plural': 'Vaccines',
            },
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='birth_country',
            field=models.CharField(default='Venezuela', max_length=100, verbose_name='País de nacimiento'),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='birth_place',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lugar de nacimiento'),
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_country',
            field=models.CharField(default='Venezuela', max_length=100, verbose_name='País de nacimiento'),
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_place',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lugar de nacimiento'),
        ),
        migrations.CreateModel(
            name='FamilyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=255)),
                ('relative', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_history', to='core.patient')),
            ],
            options={
                'verbose_name': 'Family History',
                'verbose_name_plural': 'Family Histories',
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('tabaco', 'Tabaco'), ('alcohol', 'Alcohol'), ('actividad_fisica', 'Actividad física'), ('dieta', 'Dieta'), ('sueno', 'Sueño')], max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to='core.patient')),
            ],
            options={
                'verbose_name': 'Habit',
                'verbose_name_plural': 'Habits',
            },
        ),
        migrations.CreateModel(
            name='PersonalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('patologico', 'Patológico'), ('no_patologico', 'No patológico'), ('quirurgico', 'Quirúrgico'), ('traumatico', 'Traumático'), ('alergico', 'Alérgico'), ('toxico', 'Tóxico'), ('gineco_obstetrico', 'Gineco-Obstétrico')], max_length=50)),
                ('description', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_history', to='core.patient')),
            ],
            options={
                'verbose_name': 'Personal History',
                'verbose_name_plural': 'Personal Histories',
            },
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('hospital', models.CharField(blank=True, max_length=255, null=True)),
                ('complications', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgeries', to='core.patient')),
            ],
            options={
                'verbose_name': 'Surgery',
                'verbose_name_plural': 'Surgeries',
            },
        ),
        migrations.CreateModel(
            name='VaccinationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_age_months', models.PositiveIntegerField()),
                ('dose_number', models.PositiveIntegerField()),
                ('country', models.CharField(default='Venezuela', max_length=100)),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='core.vaccine')),
            ],
            options={
                'verbose_name': 'Vaccination Schedule',
                'verbose_name_plural': 'Vaccination Schedules',
                'ordering': ['recommended_age_months', 'dose_number'],
            },
        ),
        migrations.CreateModel(
            name='PatientVaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_number', models.PositiveIntegerField()),
                ('date_administered', models.DateField()),
                ('lot', models.CharField(blank=True, max_length=100, null=True)),
                ('center', models.CharField(blank=True, max_length=255, null=True)),
                ('next_dose_date', models.DateField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='core.patient')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vaccine')),
            ],
            options={
                'verbose_name': 'Patient Vaccination',
                'verbose_name_plural': 'Patient Vaccinations',
                'unique_together': {('patient', 'vaccine', 'dose_number')},
            },
        ),
    ]
