# Generated by Django 5.2.7 on 2025-12-26 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_city_country_neighborhood_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patient',
            table='patients',
        ),
    ]
