# Generated by Django 5.2.7 on 2025-12-27 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_municipality'),
    ]

    operations = [
        migrations.AddField(
            model_name='parish',
            name='municipality',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='parishes',
                to='core.municipality'
            ),
        ),
        migrations.RemoveField(
            model_name='parish',
            name='city',
        ),
    ]
