# Generated by Django 5.2.7 on 2025-12-27 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_parish_unique_together_parish_municipality_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parish',
            options={
                'verbose_name': 'Parish',
                'verbose_name_plural': 'Parishes',
                'db_table': 'parroquias',
                'unique_together': {('municipality', 'name')},
            },
        ),
    ]
