# Generated by Django 5.2.7 on 2025-12-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_parish_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parish',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='parish',
            constraint=models.UniqueConstraint(fields=('municipality', 'name'), name='unique_parish_per_municipality'),
        ),
    ]
