# Generated by Django 5.2.7 on 2025-12-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_parish_unique_together_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='neighborhood',
            constraint=models.UniqueConstraint(
                fields=['parish', 'name'],
                name='unique_neighborhood_per_parish',
            ),
        ),
    ]
