# Generated by Django 5.2.7 on 2025-12-27 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_parish_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='neighborhood',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='parish',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='parish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighborhoods', to='core.parish'),
        ),
        migrations.AddConstraint(
            model_name='neighborhood',
            constraint=models.UniqueConstraint(fields=('parish', 'name'), name='unique_neighborhood_per_parish'),
        ),
    ]
