# Generated by Django 5.2.7 on 2025-12-28 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_neighborhood_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='neighborhood',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='parish',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección detallada'),
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección detallada'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='parish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighborhoods', to='core.parish'),
        ),
    ]
