"""
Django settings for medops project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from dotenv import load_dotenv

# === Paths ===
BASE_DIR = Path(__file__).resolve().parent.parent

# === Entorno ===
# Selecciona .env según DJANGO_ENV (development o production)
ENVIRONMENT = os.environ.get("DJANGO_ENV", "development")
load_dotenv(BASE_DIR / f".env.{ENVIRONMENT}")

# === Seguridad ===
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "inseguro-en-dev")
if SECRET_KEY == "inseguro-en-dev":
    raise ValueError("SECRET_KEY insegura: define DJANGO_SECRET_KEY en tu .env")

DEBUG = os.environ.get("DEBUG", "False") == "True"

# === Admin API Keys ===
ADMIN_API_KEY = os.environ.get("ADMIN_API_KEY", "")

# Ajuste para Docker y local
ALLOWED_HOSTS = os.environ.get(
    "ALLOWED_HOSTS", "localhost,127.0.0.1,0.0.0.0,verify.medopz.com"
).split(",")

# === SITE URL (para callback URLs de webhooks y P2C) ===
SITE_URL = os.environ.get("SITE_URL", "https://medopz.com")

# === Apps ===
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Herramientas de Terceros
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "drf_spectacular",
    "drf_spectacular_sidecar",
    "django_filters",
    "django_extensions",
    "simple_history",
    "rangefilter",
    "rest_framework_simplejwt",
    # App Principal
    "core.apps.CoreConfig",
]

# === Middleware ===
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # ✅ Siempre antes de CommonMiddleware
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "core.middleware.JWTRoleValidationMiddleware",
    "core.middleware.InstitutionPermissionMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
]

# === Ajustes Críticos para CORS y Docker ===
APPEND_SLASH = False  # ✅ FIX: Evita redirecciones 301 que rompen el pre-flight de CORS
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# === DRF / API ===
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "DATETIME_FORMAT": "%Y-%m-%dT%H:%M:%S%z",
}

if not DEBUG:
    # ✅ EN PRODUCCIÓN (DEBUG=False): Autenticación HABILITADA
    REST_FRAMEWORK.update(
        {
            "DEFAULT_AUTHENTICATION_CLASSES": [
                "rest_framework.authentication.TokenAuthentication",
                "rest_framework_simplejwt.authentication.JWTAuthentication",
            ],
            "DEFAULT_PERMISSION_CLASSES": [
                "rest_framework.permissions.IsAuthenticated",
            ],
        }
    )
    print("[PRODUCCION] Autenticacion HABILITADA")
else:
    # ✅ EN DESARROLLO (DEBUG=True): Autenticación DESHABILITADA para pruebas
    REST_FRAMEWORK.update(
        {
            "DEFAULT_AUTHENTICATION_CLASSES": [
                "rest_framework.authentication.TokenAuthentication",
                "rest_framework_simplejwt.authentication.JWTAuthentication",
            ],
            "DEFAULT_PERMISSION_CLASSES": [
                "rest_framework.permissions.AllowAny",
            ],
        }
    )
    print("[DESARROLLO] Autenticacion DESHABILITADA")

# OpenAPI Settings
SPECTACULAR_SETTINGS = {
    "TITLE": "MEDOPZ API",
    "DESCRIPTION": "Documentación de la API de MEDOPZ",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": r"/api",
    "SECURITY": [{"tokenAuth": []}],
    "SWAGGER_UI_DIST": "SIDECAR",
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
    "REDOC_DIST": "SIDECAR",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "TOKEN_TYPE_CLAIM": "token_type",
    "JTI_CLAIM": "jti",
}

# === Seguridad Extra (Fixes para Localhost) ===
X_FRAME_OPTIONS = "DENY"
SECURE_BROWSER_XSS_FILTER = True

# ✅ FIX: Desactivamos el forzado de SSL en local para que no bloquee el fetch http://
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
SECURE_SSL_REDIRECT = False  # 🚨 FIX CRÍTICO: Evita el error "Redirect not allowed"
SECURE_HSTS_SECONDS = 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False

ROOT_URLCONF = "medops.urls"

# === Templates ===
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "core" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "medops.wsgi.application"

# === Base de Datos ===
if ENVIRONMENT == "development":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("DB_NAME"),
            "USER": os.environ.get("DB_USER"),
            "PASSWORD": os.environ.get("DB_PASSWORD"),
            "HOST": os.environ.get("DB_HOST", "db"),
            "PORT": os.environ.get("DB_PORT", "5432"),
        }
    }

# === Internacionalización ===
LANGUAGE_CODE = "es-ve"
TIME_ZONE = "America/Caracas"
USE_I18N = True
USE_TZ = True

# === Static & Media ===
STATIC_URL = "/static/"
FRONTEND_ASSETS_DIR = BASE_DIR / "frontend" / "medops" / "dist" / "assets"
STATICFILES_DIRS = [FRONTEND_ASSETS_DIR] if FRONTEND_ASSETS_DIR.exists() else []
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# === CORS / CSRF (desde environment para producción) ===
_cors_origins = os.environ.get("CORS_ALLOWED_ORIGINS", "")
CORS_ALLOWED_ORIGINS = (
    [origin.strip() for origin in _cors_origins.split(",") if origin.strip()]
    if _cors_origins
    else [
        "http://localhost:5173",
        "http://localhost:8080",
        "http://127.0.0.1:8080",
        "http://127.0.0.1:5173",
    ]
)
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
CORS_ALLOW_HEADERS = [
    "accept",
    "authorization",
    "content-type",
    "user-agent",
    "x-csrfToken",
    "x-requested-with",
    "origin",
    "x-institution-id",
    "x-doctor-id",
    "x-portal",
]
_csrf_origins = os.environ.get("CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS = (
    [origin.strip() for origin in _csrf_origins.split(",") if origin.strip()]
    if _csrf_origins
    else [
        "http://localhost:5173",
        "http://localhost:8080",
        "http://127.0.0.1:8080",
    ]
)

# === ICD API ===
ICD_CLIENT_ID = os.environ.get("ICD_CLIENT_ID")
ICD_CLIENT_SECRET = os.environ.get("ICD_CLIENT_SECRET")
ICD_API_BASE_ES = os.environ.get("ICD_API_BASE_ES", "http://icdapi_es/icd")
ICD_API_BASE_EN = os.environ.get("ICD_API_BASE_EN", "http://icdapi_en/icd")

# === Email Configuration (Resend SMTP) ===
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.resend.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "resend"
EMAIL_HOST_PASSWORD = os.environ.get("RESEND_API_KEY", "")
DEFAULT_FROM_EMAIL = "admin@medopz.com"
SERVER_EMAIL = DEFAULT_FROM_EMAIL

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file": {
            "class": "logging.FileHandler",
            "filename": BASE_DIR / "django_error.log",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console", "file"],
            "level": "ERROR",  # Captura errores de petición (500, 404, etc.)
            "propagate": False,
        },
        "django.security": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "core": {  # Tu app principal
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}


# === CELERY CONFIGURACIÓN (preparado para activar con Redis) ===
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://redis:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "redis://redis:6379/0")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "America/Caracas"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutos máximo por tarea


# =====================================================
# SNOMED CT Configuration
# =====================================================
SNOWSTORM_URL = os.environ.get("SNOWSTORM_URL", "http://localhost:8080")
SNOMED_ENABLED = os.environ.get("SNOMED_ENABLED", "False").lower() == "true"


# =====================================================
# Sentry Error Tracking (Observabilidad CEO/CTO)
# =====================================================
SENTRY_DSN = os.environ.get("SENTRY_DSN", "")
if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        traces_sample_rate=0.1,
        send_default_pii=False,
        environment=ENVIRONMENT,
        release=os.environ.get("GIT_COMMIT_SHA", "unknown"),
    )
    print(f"[SENTRY] Monitorización habilitada para entorno: {ENVIRONMENT}")


# =====================================================
# Cloudflare R2 Configuration
# =====================================================
CLOUDFLARE_R2_ACCOUNT_ID = os.environ.get("CLOUDFLARE_R2_ACCOUNT_ID", "")
CLOUDFLARE_R2_ACCESS_KEY_ID = os.environ.get("CLOUDFLARE_R2_ACCESS_KEY_ID", "")
CLOUDFLARE_R2_SECRET_ACCESS_KEY = os.environ.get("CLOUDFLARE_R2_SECRET_ACCESS_KEY", "")
CLOUDFLARE_R2_BUCKET_NAME = os.environ.get(
    "CLOUDFLARE_R2_BUCKET_NAME", "medops-documents"
)
CLOUDFLARE_R2_ENDPOINT_URL = os.environ.get(
    "CLOUDFLARE_R2_ENDPOINT_URL",
    f"https://{CLOUDFLARE_R2_ACCOUNT_ID}.r2.cloudflarestorage.com"
    if CLOUDFLARE_R2_ACCOUNT_ID
    else "",
)

R2_ENABLED = all(
    [
        CLOUDFLARE_R2_ACCOUNT_ID,
        CLOUDFLARE_R2_ACCESS_KEY_ID,
        CLOUDFLARE_R2_SECRET_ACCESS_KEY,
    ]
)

CLOUDFLARE_R2_PUBLIC_URL_BASE = os.environ.get("CLOUDFLARE_R2_PUBLIC_URL_BASE", "")
