"""
Django settings for medops project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# === Paths ===
BASE_DIR = Path(__file__).resolve().parent.parent

# === Entorno ===
# Selecciona .env según DJANGO_ENV (development o production)
ENVIRONMENT = os.environ.get("DJANGO_ENV", "development")
load_dotenv(BASE_DIR / f".env.{ENVIRONMENT}")

# === Seguridad ===
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "inseguro-en-dev")
if SECRET_KEY == "inseguro-en-dev":
    raise ValueError("SECRET_KEY insegura: define DJANGO_SECRET_KEY en tu .env")

DEBUG = os.environ.get("DEBUG", "False") == "True"

# Ajuste para Docker y local
ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1,0.0.0.0").split(",")

# === Apps ===
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Herramientas de Terceros
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'drf_spectacular',
    'drf_spectacular_sidecar',
    'django_filters',
    'django_extensions',
    'simple_history',
    'rangefilter',
    
    # App Principal
    'core.apps.CoreConfig',
]

# === Middleware ===
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # ✅ Siempre antes de CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.InstitutionPermissionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]

# === Ajustes Críticos para CORS y Docker ===
APPEND_SLASH = False  # ✅ FIX: Evita redirecciones 301 que rompen el pre-flight de CORS
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# === DRF / API ===
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "DATETIME_FORMAT": "%Y-%m-%dT%H:%M:%S%z",
}

if not DEBUG:
    # ✅ EN PRODUCCIÓN (DEBUG=False): Autenticación HABILITADA
    REST_FRAMEWORK.update({
        "DEFAULT_AUTHENTICATION_CLASSES": [
            "rest_framework.authentication.TokenAuthentication",
        ],
        "DEFAULT_PERMISSION_CLASSES": [
            "rest_framework.permissions.IsAuthenticatedOrReadOnly",
        ],
    })
    print("[PRODUCCION] Autenticacion HABILITADA")
else:
    # ✅ EN DESARROLLO (DEBUG=True): Autenticación DESHABILITADA para pruebas
    REST_FRAMEWORK.update({
        "DEFAULT_AUTHENTICATION_CLASSES": [],
        "DEFAULT_PERMISSION_CLASSES": [
            "rest_framework.permissions.AllowAny",
        ],
    })
    print("[DESARROLLO] Autenticacion DESHABILITADA")

# OpenAPI Settings
SPECTACULAR_SETTINGS = {
    "TITLE": "MedOps API",
    "DESCRIPTION": "Documentación de la API de MedOps",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": r"/api",
    "SECURITY": [{"tokenAuth": []}],
    "SWAGGER_UI_DIST": "SIDECAR",
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
    "REDOC_DIST": "SIDECAR",
}

# === Seguridad Extra (Fixes para Localhost) ===
X_FRAME_OPTIONS = "DENY"
SECURE_BROWSER_XSS_FILTER = True

# ✅ FIX: Desactivamos el forzado de SSL en local para que no bloquee el fetch http://
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
SECURE_SSL_REDIRECT = False  # 🚨 FIX CRÍTICO: Evita el error "Redirect not allowed"
SECURE_HSTS_SECONDS = 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False

ROOT_URLCONF = 'medops.urls'

# === Templates ===
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "core" / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'medops.wsgi.application'

# === Base de Datos ===
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DB_NAME"),
        "USER": os.environ.get("DB_USER"),
        "PASSWORD": os.environ.get("DB_PASSWORD"),
        "HOST": os.environ.get("DB_HOST", "db"),
        "PORT": os.environ.get("DB_PORT", "5432"),
    }
}

# === Internacionalización ===
LANGUAGE_CODE = 'es-ve'
TIME_ZONE = 'America/Caracas'
USE_I18N = True
USE_TZ = True

# === Static & Media ===
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "frontend" / "medops" / "dist" / "assets"]
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# === CORS / CSRF ===
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:8080",
    "http://127.0.0.1:8080",
    "http://127.0.0.1:5173",
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
CORS_ALLOW_HEADERS = [
    "accept", "authorization", "content-type", "user-agent",
    "x-csrfToken", "x-requested-with", "origin", "x-institution-id",
    "x-doctor-id",
]
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:8080",
    "http://127.0.0.1:8080",
]

# === ICD API ===
ICD_CLIENT_ID = os.environ.get("ICD_CLIENT_ID")
ICD_CLIENT_SECRET = os.environ.get("ICD_CLIENT_SECRET")
ICD_API_BASE_ES = os.environ.get("ICD_API_BASE_ES", "http://icdapi_es/icd")
ICD_API_BASE_EN = os.environ.get("ICD_API_BASE_EN", "http://icdapi_en/icd")